"use strict";
const path=require("node:path");
const STOP=new Set(["the","and","for","with","from","this","that","into","を","に","の","は","が","と","で"]);
function norm(s){return String(s??"").normalize("NFKC").toLowerCase();}
function buildQueryProfile(task){const text=norm(task);const terms=[...new Set((text.match(/[\p{L}\p{N}_.$/-]{2,}/gu)||[]).map(x=>x.replace(/^[-./]+|[-./]+$/g,"")).filter(x=>x&&!STOP.has(x)))].slice(0,64);return {terms,raw:text};}
function scoreCandidate(rel,content,profile){const p=norm(rel).replaceAll("\\","/"),b=path.posix.basename(p),body=norm(content).slice(0,70000);let score=0;for(const t of profile?.terms||[]){if(!t)continue;if(b.includes(t))score+=12;if(p.includes(t))score+=7;let i=0,c=0;while((i=body.indexOf(t,i))>=0&&c<12){score+=2;c++;i+=Math.max(t.length,1);}}if(/(?:test|spec)\./.test(b))score+=1;return score;}
function applyRelationBoost(candidates){const top=[...candidates].sort((a,b)=>b.score-a.score).slice(0,8);const stems=new Set(top.map(x=>path.posix.basename(x.rel).replace(/\.(?:test|spec)?\.[^.]+$|\.[^.]+$/,"").replace(/\.$/,"")));for(const c of candidates){const base=path.posix.basename(c.rel);for(const s of stems)if(s&&base.includes(s)&&!top.includes(c))c.score+=3;}return candidates;}
function makeExcerpt(source,profile,limit=1800){source=String(source??"");if(source.length<=limit)return source;const low=norm(source);let hits=[];for(const t of profile?.terms||[]){let i=low.indexOf(t);if(i>=0)hits.push(i);}if(!hits.length)return source.slice(0,limit);hits.sort((a,b)=>a-b);const chunks=[];for(const h of hits.slice(0,5)){const a=Math.max(0,h-Math.floor(limit/6)),b=Math.min(source.length,a+Math.floor(limit/3));chunks.push(source.slice(a,b));}let out=chunks.join("\n[...snip...]\n");return out.slice(0,limit);}
function selectCandidates(candidates,{maxFiles=8,maxChars=12000}={}){const sorted=[...candidates].sort((a,b)=>b.score-a.score||a.rel.localeCompare(b.rel));let chars=0,out=[];for(const c of sorted){const text=String(c.content??"");if(out.length>=maxFiles)break;if(out.length&&chars+text.length>maxChars)continue;out.push(c);chars+=text.length;}return out;}
module.exports={buildQueryProfile,scoreCandidate,applyRelationBoost,makeExcerpt,selectCandidates};
