"use strict";
const path=require("node:path");
const {createAiCoreAdapter}=require("./adapters/ai-core.js");
const {createEvidenceSearchAdapter}=require("./adapters/evidence-search.js");
const {createTgserverAdapter}=require("./adapters/tgserver.js");
const {createExternalReviewAdapter}=require("./adapters/external-review.js");
const {PatchService}=require("./patch-service.js");
const {RuntimeEvidenceStore}=require("./runtime-evidence.js");
const {RunAuthority}=require("./run-authority.js");
const {RepoPolicy}=require("./repo-policy.js");
const {createWorkflow}=require("./workflow.js");
const {createServer}=require("./http.js");
const {sourceGate}=require("./gates.js");
const {createSandboxVerificationLane}=require("./control/sandbox-verification.js");
const {createDapEvidenceLane}=require("./control/dap-evidence-runtime.js");
const {DurableWriterLock}=require("../orchestrator/durable-writer-lock.js");
const {DurableFileIO}=require("../orchestrator/durable-file-io.js");

const root=process.cwd(),runtimeRoot=process.env.DEBUG_AI_RUNTIME_ROOT||path.join(root,"runtime");
const gate=sourceGate(root);if(!gate.pass)throw new Error(`SOURCE_GATE_FAILED:${gate.failures.join(",")}`);
const repoPolicy=new RepoPolicy();
const writerLock=DurableWriterLock.acquire({root:path.join(runtimeRoot,"durable")});
const durableIo=new DurableFileIO({writerLock});
const authority=new RunAuthority({runtimeRoot,repoPolicy,durableIo});
const aiCore=createAiCoreAdapter();
if(!process.env.DEBUG_AI_EVIDENCE_SEARCH_URL)throw new Error("EVIDENCE_SEARCH_URL_REQUIRED");
const evidenceSearch=createEvidenceSearchAdapter();
if(!process.env.DEBUG_AI_TGSERVER_URL)throw new Error("TGSERVER_URL_REQUIRED");
if(!process.env.DEBUG_AI_TGSERVER_LOG_PROJECT_ID)throw new Error("TGSERVER_LOG_PROJECT_ID_REQUIRED");
if(!process.env.DEBUG_AI_TGSERVER_KB_PROJECT_ID)throw new Error("TGSERVER_KB_PROJECT_ID_REQUIRED");
const tgserver=createTgserverAdapter();
const runtimeEvidence=new RuntimeEvidenceStore(runtimeRoot);
const sandboxVerification=createSandboxVerificationLane();
const dapEvidence=createDapEvidenceLane();
if(!process.env.GROQ_API_KEY&&!process.env.GEMINI_API_KEY)throw new Error("EXTERNAL_REVIEW_PROVIDER_REQUIRED");
const externalReview=createExternalReviewAdapter();
const patchService=new PatchService({runtimeRoot,repoPolicy});
const workflow=createWorkflow({aiCore,externalReview,evidenceSearch,runtimeEvidence,tgserver,patchService,authority,repoPolicy,sandboxVerification,dapEvidence});
const host=process.env.DEBUG_AI_HOST||"127.0.0.1",port=Number(process.env.DEBUG_AI_PORT||8787);
const server=createServer({workflow,host,port});
let shuttingDown=false;
function shutdown(signal){if(shuttingDown)return;shuttingDown=true;server.close(()=>{try{writerLock.close();}finally{process.exit(0);}});setTimeout(()=>{try{writerLock.close();}finally{process.exit(1);}},5000).unref();if(signal)console.error(`DebugAI shutdown: ${signal}`);}
process.once("SIGTERM",()=>shutdown("SIGTERM"));
process.once("SIGINT",()=>shutdown("SIGINT"));
async function start(){const recovery=await workflow.recoverStartup();if(recovery.claimed.length||recovery.incompatible.length)console.log(`DebugAI startup recovery: claimed=${recovery.claimed.length} incompatible=${recovery.incompatible.length}`);server.listen(port,host,()=>console.log(`DebugAI listening on http://${host}:${port}`));}
void start().catch(error=>{console.error(`DebugAI startup failed: ${String(error?.message||error)}`);try{writerLock.close();}finally{process.exitCode=1;}});
