"use strict";
const path=require("node:path");
const {createAiCoreAdapter}=require("./adapters/ai-core.js");
const {createEvidenceSearchAdapter}=require("./adapters/evidence-search.js");
const {createEvaluatorAdapter}=require("./adapters/evaluator.js");
const {createTgserverAdapter}=require("./adapters/tgserver.js");
const {createExternalReviewAdapter}=require("./adapters/external-review.js");
const {createBenchmarkService}=require("./benchmark/service.js");
const {PatchService}=require("./patch-service.js");
const {RuntimeEvidenceStore}=require("./runtime-evidence.js");
const {RunAuthority}=require("./run-authority.js");
const {RepoPolicy}=require("./repo-policy.js");
const {createWorkflow}=require("./workflow.js");
const {createServer}=require("./http.js");
const {sourceGate}=require("./gates.js");
const root=process.cwd(),runtimeRoot=process.env.DEBUG_AI_RUNTIME_ROOT||path.join(root,"runtime");
const gate=sourceGate(root);if(!gate.pass)throw new Error(`SOURCE_GATE_FAILED:${gate.failures.join(",")}`);
const repoPolicy=new RepoPolicy(),authority=new RunAuthority({runtimeRoot,repoPolicy}),aiCore=createAiCoreAdapter();
if(!process.env.DEBUG_AI_EVIDENCE_SEARCH_URL)throw new Error("EVIDENCE_SEARCH_URL_REQUIRED");
const evidenceSearch=createEvidenceSearchAdapter(),evaluator=createEvaluatorAdapter();
if(!process.env.DEBUG_AI_TGSERVER_URL)throw new Error("TGSERVER_URL_REQUIRED");
if(!process.env.DEBUG_AI_TGSERVER_LOG_PROJECT_ID)throw new Error("TGSERVER_LOG_PROJECT_ID_REQUIRED");
if(!process.env.DEBUG_AI_TGSERVER_KB_PROJECT_ID)throw new Error("TGSERVER_KB_PROJECT_ID_REQUIRED");
const tgserver=createTgserverAdapter(),benchmarkService=createBenchmarkService({evaluator,tgTelemetry:tgserver}),runtimeEvidence=new RuntimeEvidenceStore(runtimeRoot);
if(!process.env.GROQ_API_KEY&&!process.env.GEMINI_API_KEY)throw new Error("EXTERNAL_REVIEW_PROVIDER_REQUIRED");
const externalReview=createExternalReviewAdapter(),patchService=new PatchService({runtimeRoot,repoPolicy});
const workflow=createWorkflow({aiCore,externalReview,evidenceSearch,runtimeEvidence,tgserver,patchService,authority});
const host=process.env.DEBUG_AI_HOST||"127.0.0.1",port=Number(process.env.DEBUG_AI_PORT||8787);
createServer({workflow,benchmarkService,host,port}).listen(port,host,()=>console.log(`DebugAI listening on http://${host}:${port}`));
