"use strict";
const crypto=require("node:crypto");
const path=require("node:path");
const {contentHash,WorkflowStepId,StepPhase}=require("../orchestrator/durable-contracts.js");
const {buildDownstreamInputBundle}=require("../orchestrator/role-result.js");
const {assertPromotable}=require("./asset-promotion.js");
const {createReadOnlyToolRuntime,assertToolResultIntegrity,readText,testInventory,blockedReadPath}=require("./control/read-only-tool-runtime.js");
const {runRoleWithReadOnlyTools,mergeEvidenceIds}=require("./control/tool-loop.js");
const {parseAndValidateRoleOutput}=require("./control/role-output-validator.js");
const {getRoleRuntimeBudget}=require("./control/role-runtime-budgets.js");
const {registerEvidenceList,evidenceIds,registrySummary}=require("./control/evidence-registry.js");
const {runResearcherContinuation}=require("./control/researcher-continuation.js");
const {createDurableToolEffectHooks,toolResultPath,TOOL_CONTRACT_VERSION}=require("./control/durable-tool-effects.js");
const {ROLE_CONTRACT_VERSION}=require("./control/role-contracts.js");
const {makeDurableAnalysisInput,loadDurableAnalysisInput}=require("./control/durable-workflow-input.js");
const {makeDurableWorkflowStage,loadDurableWorkflowStage}=require("./control/durable-workflow-stage.js");
const {buildCompletionGateInput,evaluateCompletionGate}=require("./control/completion-gate.js");
const {makePatchPacket,makeReviewPacket,publicReviewPacketSummary}=require("./control/runtime-packets.js");
const {repositorySnapshotId}=require("./control/repository-snapshot.js");
const CAUSAL_SCOUT_OUTPUT_POLICY="Causal Scout. Return JSON only. Final output requires a top-level claims array. Every claims[] item requires type and statement. Causal candidates must use type HYPOTHESIS and a concrete falsification_condition; cite only registered evidence_refs when available. A falsification condition must name an observation that contradicts the hypothesis, rather than one that supports it. Keep proposed observations within existing read-only tools and security restrictions; never propose relaxing seccomp or other safety controls. Use type UNKNOWN for unresolved evidence gaps instead of inventing a cause, and retain rejected hypotheses with their counter_evidence_refs. An empty claims array is valid when no supported candidate or material unknown remains. Never emit confirmed_root_cause or patch/apply/deploy operations. Tool-request rounds use the existing tool_requests protocol; the claims requirement applies to final output.";

function parseJson(c){if(typeof c!=="string")return c;return JSON.parse(c.trim().replace(/^```json\s*/i,"").replace(/```$/i,"").trim());}
function roleOutput(call,role){if(call?.validated_output&&typeof call.validated_output==="object")return call.validated_output;return parseAndValidateRoleOutput(role,call?.content,{availableEvidenceIds:call?.tool_loop?.evidence_ids||[]});}
function toolEvidenceRecords(call){
  const out=[],seen=new Set();
  for(const observation of call?.tool_loop?.observations||[])for(const item of observation.results||[]){const result=item?.result;if(result?.status!=="OK")continue;assertToolResultIntegrity(result);if(seen.has(result.evidence_id))continue;seen.add(result.evidence_id);out.push({evidence_id:result.evidence_id,tool:result.tool,data:result.data,integrity:result.integrity});}
  return out;
}
function toolAudit(call){const loop=call?.tool_loop;if(!loop)return null;const tools=[];for(const observation of loop.observations||[])for(const item of observation.results||[]){const tool=item?.request?.tool;if(tool&&!tools.includes(tool))tools.push(tool);}return {rounds:Number(loop.rounds||0),total_calls:Number(loop.total_calls||0),evidence_ids:[...(loop.evidence_ids||[])],base_evidence_ids:[...(loop.base_evidence_ids||[])],tool_evidence_ids:[...(loop.tool_evidence_ids||[])],selected_skill_ids:[...(loop.selected_skill_ids||[])],tools,progress:loop.progress||null};}
function pickDiagnosisStatement(diagnosisJson){if(diagnosisJson?.public_statement)return String(diagnosisJson.public_statement);if(diagnosisJson?.hypothesis)return String(diagnosisJson.hypothesis);if(Array.isArray(diagnosisJson?.diagnoses)&&diagnosisJson.diagnoses[0]?.hypothesis)return String(diagnosisJson.diagnoses[0].hypothesis);return "behavioral mismatch";}
function publicLocalEvidence(localEvidence){return (Array.isArray(localEvidence)?localEvidence:[]).map((item,index)=>({id:String(item?.id||`L${String(index+1).padStart(3,"0")}`),kind:String(item?.kind||"local"),observation:String(item?.observation||item?.summary||"")})).filter(item=>item.observation);}
function dapFailureChecks(failure,deterministicChecks){
  const checks=Array.isArray(deterministicChecks)?deterministicChecks:[];
  if(checks.some(item=>String(item?.status||"").toUpperCase()==="FAIL"))return checks;
  if(!failure||typeof failure!=="object")return checks;
  return [{status:"FAIL",check_type:String(failure.check_type||failure.kind||failure.type||"runtime"),name:String(failure.name||"reported failure"),reason:String(failure.message||failure.summary||failure.reason||""),stderr:String(failure.stderr||""),stdout:String(failure.stdout||"")}];
}
function activeDapHint(evidence){return evidence&&evidence.authority==="HINT_ONLY"&&evidence.local_only===true&&evidence.status!=="NOT_CONFIGURED"?evidence:null;}
function dapHintProtocol(hint){return hint?"DAP_HINT_AUTHORITY=HINT_ONLY. The dap_hint object is local runtime diagnostic data, not registered claim evidence. Never cite dap_hint as FACT, INFERENCE, or REJECTED evidence. Use it only to form/falsify hypotheses or to decide which registered evidence to gather next.":"";}
function reviewStreamEvidence(value,{includeExcerpt=false,maxExcerptChars=1200}={}){
  const text=String(value||"");
  return {bytes:Buffer.byteLength(text,"utf8"),sha256:crypto.createHash("sha256").update(text).digest("hex"),excerpt:includeExcerpt?text.slice(-maxExcerptChars):null};
}
function reviewableVerificationCheck(check){
  const item=check&&typeof check==="object"?check:{};const status=String(item.status||"").toUpperCase(),includeExcerpt=status!=="PASS";
  return {...item,stdout:reviewStreamEvidence(item.stdout,{includeExcerpt}),stderr:reviewStreamEvidence(item.stderr,{includeExcerpt})};
}
function evidencePromptView(records){return (Array.isArray(records)?records:[]).map(record=>{if(!record||typeof record!=="object")return record;const {integrity,...view}=record;return view;});}
function patchPacketSource(repo,selectedPaths){
  const sourceExcerpts=[],preconditionHashes={},prohibitedPaths=[];
  for(const value of Array.isArray(selectedPaths)?selectedPaths:[]){
    const rel=String(value||"");
    let prohibited=false;try{prohibited=blockedReadPath(rel);}catch{prohibited=true;}
    if(prohibited){prohibitedPaths.push(rel);continue;}
    try{const item=readText(repo,rel,{maxChars:8000});sourceExcerpts.push({path:item.path,sha256:item.sha256,size:item.size,excerpt:item.content,truncated:item.truncated});preconditionHashes[item.path]=item.sha256;}
    catch(error){if(!String(error?.message||error).startsWith("READ_FILE_NOT_FOUND:"))throw error;sourceExcerpts.push({path:rel,exists:false,excerpt:""});}
  }
  return{sourceExcerpts,preconditionHashes,prohibitedPaths};
}
function patchPacketEvidenceRefs(analysis){return mergeEvidenceIds(analysis?.evidence_registry?.evidence_ids||[],analysis?.evidence_registry?.tool_evidence_ids||[]);}
function reviewPacketHashes(candidate,receipt){
  const out={};
  for(const pre of candidate?.preconditions||[])out[pre.path]={before:pre.sha256||null,after:null};
  for(const file of receipt?.files||[])out[file.path]={before:out[file.path]?.before||null,after:file.sha256||null};
  return out;
}
function reviewPacketInvariants(result){
  const out=[{name:"patch-invariants",status:result?.invariants?.pass===true?"PASS":"FAIL",failures:[...(result?.invariants?.failures||[])]}];
  for(const [name,gate] of Object.entries(result?.gates||{}))out.push({name,status:String(gate?.status||"UNKNOWN").toUpperCase()});
  return out;
}
function createWorkflow({aiCore,externalReview=null,evidenceSearch=null,runtimeEvidence=null,tgserver=null,patchService=null,authority=null,repoPolicy=null,sandboxVerification=null,dapEvidence=null,recoveryHooks=null,repositorySnapshot=repositorySnapshotId}={}){
  if(!aiCore)throw new Error("AI_CORE_ADAPTER_REQUIRED");
  const activeRuns=new Map(),backgroundErrors=new Map();
  async function logRuntime(event){if(tgserver)await tgserver.log(event);}
  function makeReadOnlyToolRuntime(repoPath){if(!repoPolicy||!repoPath)return null;return createReadOnlyToolRuntime({repo:repoPath,repoPolicy,tgserver,evidenceSearch});}
  async function callReadOnlyRole(role,{system,user},toolRuntime,{baseEvidenceIds=[],strictEvidenceRefs=true,continuationState=null,durableHooks=null}={}){return runRoleWithReadOnlyTools({aiCore,role,system,user,toolRuntime,baseEvidenceIds,strictEvidenceRefs,continuationState,durableHooks});}
  async function callDirectRole(role,{system,user}){const b=getRoleRuntimeBudget(role);return aiCore.call(role,{system,user,maxTokens:b.max_tokens,timeoutMsOverride:b.turn_timeout_ms,deadlineAt:Date.now()+b.turn_timeout_ms});}
  async function getOfficialEvidence(query){if(!evidenceSearch)return{official:[],evidenceGap:false,evidenceStatus:"NOT_CONFIGURED"};try{return{official:await evidenceSearch.search({query}),evidenceGap:false,evidenceStatus:"FINAL_VALID"};}catch(e){if(e?.code==="EVIDENCE_SEARCH_NOT_FINAL")return{official:[],evidenceGap:true,evidenceStatus:String(e?.meta?.status||"NOT_FINAL")};throw e;}}
  async function prepareAnalysis({runId=null,rawRequest="",failure=null,localEvidence=[],repo=null,projectId=null}={}){
    let authRun=null,resuming=Boolean(runId),inputRecord=null,inputManifestRef=null;
    if(!authority)return{runId:runId||crypto.randomUUID(),authRun:null,resuming,targetRepo:repoPolicy&&repo?repoPolicy.assertRepo(repo):null,input:{rawRequest:String(rawRequest||""),failure,localEvidence},inputRecord:null,inputManifestRef:null};
    if(runId)authRun=authority.load(runId);
    else{
      const masterRequest=String(rawRequest||failure?.message||failure?.summary||"");
      authRun=authority.start({rawRequest:masterRequest,repo,projectId});runId=authRun.run_id;
      authority.transition(authRun,"PARSED");authority.transition(authRun,"CONTEXT_READY");authority.transition(authRun,"VERIFYING");authority.transition(authRun,"FAILED");authority.transition(authRun,"RESOLVING");
    }
    if(!authority.durableEnabled?.())return{runId,authRun,resuming,targetRepo:authRun.project_dir,input:{rawRequest:String(rawRequest||""),failure,localEvidence},inputRecord:null,inputManifestRef:null};
    await authority.initializeDurable(authRun);
    if(!resuming){
      const made=makeDurableAnalysisInput({runId,rawRequest:String(rawRequest||failure?.message||failure?.summary||""),failure,localEvidence});
      await authority.commitDurable({runId,manifestPatch:{job:{status:"RUNNING"},workflow_input_refs:{analysis_input:made.path},workflow_cursor:{step_id:WorkflowStepId.DETERMINISTIC_VERIFY,step_phase:StepPhase.PENDING,step_input_ref:made.path,step_result_ref:null}},runStatePatch:{job_status:"RUNNING"},immutableRecords:[{path:made.path,record:made.record}]});
      inputRecord=made.record;inputManifestRef=made.path;
      return{runId,authRun,resuming,targetRepo:authRun.project_dir,input:{rawRequest:made.payload.raw_request,failure:made.payload.failure,localEvidence:made.payload.local_evidence},inputRecord,inputManifestRef};
    }
    const {state,manifest}=authority.loadDurable(runId),recordPath=manifest.workflow_input_refs?.analysis_input;
    if(state.job_status==="CANCELLED"||manifest.cancellation!==null)throw new Error("RUN_CANCELLED");
    if(["DONE","BLOCKED","FAILED"].includes(state.job_status))throw new Error(`RUN_NOT_RECOVERABLE:${state.job_status}`);
    if(typeof recordPath!=="string"||!recordPath)throw new Error("DURABLE_ANALYSIS_INPUT_REF_MISSING");
    const loaded=loadDurableAnalysisInput({authority,recordPath});inputRecord=loaded.record;inputManifestRef=recordPath;
    if(repo&&path.resolve(String(repo))!==path.resolve(authRun.project_dir))throw new Error("DURABLE_RESUME_REPO_MISMATCH");
    return{runId,authRun,resuming,targetRepo:authRun.project_dir,input:{rawRequest:loaded.payload.raw_request,failure:loaded.payload.failure,localEvidence:loaded.payload.local_evidence},inputRecord,inputManifestRef};
  }
  async function setCursor(runId,stepId,stepPhase,{stepInputRef=null,stepResultRef=null,activeRoleExecutionId=null,jobStatus="RUNNING"}={}){
    if(!authority?.durableEnabled?.())return null;
    return authority.commitDurable({runId,manifestPatch:{job:{status:jobStatus},workflow_cursor:{step_id:stepId,step_phase:stepPhase,step_input_ref:stepInputRef,step_result_ref:stepResultRef,active_role_execution_id:activeRoleExecutionId}},runStatePatch:{job_status:jobStatus}});
  }
  async function saveStage(runId,key,payload,nextStep,{activeRoleExecutionId=null}={}){
    const made=makeDurableWorkflowStage({runId,key,payload});
    await authority.commitDurable({runId,manifestPatch:{job:{status:"RUNNING"},workflow_input_refs:{[key]:made.path},workflow_cursor:{step_id:nextStep,step_phase:StepPhase.PENDING,step_input_ref:made.path,step_result_ref:null,active_role_execution_id:activeRoleExecutionId}},runStatePatch:{job_status:"RUNNING"},immutableRecords:[{path:made.path,record:made.record}]});
    return made;
  }
  function loadStageRef(runId,key){const {manifest}=authority.loadDurable(runId),ref=manifest.workflow_input_refs?.[key];return typeof ref==="string"&&ref?loadDurableWorkflowStage({authority,recordPath:ref,expectedKey:key}):null;}
  function durableResearchEvidence(roleResult){const out=[];for(const effectId of roleResult?.effect_refs||[]){const result=authority.readDurableRecord(toolResultPath(effectId),{expectedSchema:"debugai.tool-result/v1",allowMissing:true});if(!result)throw new Error(`DURABLE_EFFECT_RESULT_MISSING:${effectId}`);assertToolResultIntegrity(result);out.push({evidence_id:result.evidence_id,tool:result.tool,data:result.data,integrity:result.integrity});}return out;}
  function failClosedRecoveryError(error){return /(?:INCOMPATIBLE|MISMATCH|DIGEST|CORRUPT|SECURITY|FORBIDDEN|CANCELLED|EPOCH_FENCED|GENERATION_CONFLICT|INPUT_REF_MISSING)/i.test(String(error?.code||error?.message||error));}
  async function recordExecutionFailure(runId,error){if(!authority?.durableEnabled?.())return;const closed=failClosedRecoveryError(error),loaded=authority.loadDurable(runId),cursor=loaded.manifest.workflow_cursor,durable=error?.durable||null;await authority.commitDurable({runId,manifestPatch:{job:{status:closed?"BLOCKED":"RETRY_WAIT"},workflow_cursor:{...cursor,step_phase:closed?StepPhase.BLOCKED:StepPhase.PENDING,active_role_execution_id:durable?.role_execution_id||cursor.active_role_execution_id}},runStatePatch:{job_status:closed?"BLOCKED":"RETRY_WAIT"}});}
  async function executeAnalysis(prepared){
    const {runId,resuming,targetRepo,input,inputRecord,inputManifestRef}=prepared,{rawRequest,failure,localEvidence}=input;
    const toolRuntime=makeReadOnlyToolRuntime(targetRepo),durable=Boolean(authority?.durableEnabled?.());
    let contextStage=durable?loadStageRef(runId,"research_context"):null,context,scouts=null;
    if(contextStage){
      context=contextStage.payload;const currentSnapshot=repositorySnapshot(targetRepo);if(currentSnapshot!==context.repo_snapshot_id)throw new Error("DURABLE_REPO_SNAPSHOT_MISMATCH");
    }else{
      if(durable)await setCursor(runId,WorkflowStepId.DETERMINISTIC_VERIFY,StepPhase.RUNNING,{stepInputRef:inputManifestRef});
      const deterministicVerification=sandboxVerification&&targetRepo?await sandboxVerification.collect(targetRepo):{status:"NOT_CONFIGURED",checks:[]};
      const deterministicChecks=Array.isArray(deterministicVerification?.checks)?deterministicVerification.checks:[];
      if(deterministicChecks.length)runtimeEvidence?.write(runId,"deterministic_verification",{status:deterministicVerification.status,checks:deterministicChecks});
      let dapHint=null;if(dapEvidence&&targetRepo){const candidate=await dapEvidence.collect({repo:targetRepo,checks:dapFailureChecks(failure,deterministicChecks),task:String(rawRequest||failure?.message||failure?.summary||""),variableNames:Array.isArray(failure?.variable_names)?failure.variable_names:[]});dapHint=activeDapHint(candidate);if(dapHint){runtimeEvidence?.write(runId,"dap_hint",dapHint);await logRuntime({run_id:runId,severity:dapHint.status==="PASS"?"info":"warn",kind:"dap_hint",authority:"HINT_ONLY",local_only:true,status:dapHint.status,reason:dapHint.reason,target:dapHint.target||null});}}
      const hintProtocol=dapHintProtocol(dapHint),localRecords=registerEvidenceList("LOCAL_RUNTIME",[...(Array.isArray(localEvidence)?localEvidence:[]),...deterministicChecks.map(reviewableVerificationCheck)]),localIds=evidenceIds(localRecords);
      runtimeEvidence?.write(runId,"failure",failure);await logRuntime({run_id:runId,severity:"error",kind:"failure",failure});if(deterministicChecks.length)await logRuntime({run_id:runId,severity:deterministicChecks.some(x=>x.status==="FAIL")?"warn":"info",kind:"deterministic_verification",status:deterministicVerification.status,check_count:deterministicChecks.length,failed:deterministicChecks.filter(x=>x.status==="FAIL").length});
      const query=String(failure?.message||failure?.summary||rawRequest||"debug failure");
      const combined=await Promise.all([Promise.all([callReadOnlyRole("code_scout",{system:["Code Scout. Return one compact JSON object under 400 tokens. Use at most 3 items per array and concise strings. No prose outside JSON.",hintProtocol].filter(Boolean).join("\n"),user:JSON.stringify({task:rawRequest,failure,evidence:evidencePromptView(localRecords),dap_hint:dapHint})},toolRuntime,{baseEvidenceIds:localIds}),callReadOnlyRole("causal_scout",{system:[CAUSAL_SCOUT_OUTPUT_POLICY,hintProtocol].filter(Boolean).join("\n"),user:JSON.stringify({task:rawRequest,failure,evidence:evidencePromptView(localRecords),dap_hint:dapHint})},toolRuntime,{baseEvidenceIds:localIds})]),tgserver?tgserver.search(query):Promise.resolve([]),getOfficialEvidence(query)]);scouts=combined[0];const knownKnowledge=combined[1],evidenceResult=combined[2];
      const scoutJson=[roleOutput(scouts[0],"code_scout"),roleOutput(scouts[1],"causal_scout")],scoutToolEvidence=[...toolEvidenceRecords(scouts[0]),...toolEvidenceRecords(scouts[1])],official=evidenceResult.official,evidenceGap=evidenceResult.evidenceGap,evidenceStatus=evidenceResult.evidenceStatus,knowledgeRecords=registerEvidenceList("INTERNAL_KB",knownKnowledge),officialRecords=registerEvidenceList("OFFICIAL_EXTERNAL",official),researchBase=mergeEvidenceIds(localIds,evidenceIds(knowledgeRecords),evidenceIds(officialRecords),scoutToolEvidence.map(x=>x.evidence_id));
      context={repo_snapshot_id:durable?repositorySnapshot(targetRepo):null,deterministic_verification:deterministicVerification,deterministic_checks:deterministicChecks,dap_hint:dapHint,local_records:localRecords,local_ids:localIds,query,scout_json:scoutJson,scout_tool_evidence:scoutToolEvidence,scout_tool_audit:{code_scout:toolAudit(scouts[0]),causal_scout:toolAudit(scouts[1])},known_knowledge:knownKnowledge,knowledge_records:knowledgeRecords,official,evidence_gap:evidenceGap,evidence_status:evidenceStatus,official_records:officialRecords,research_base:researchBase};
      if(durable)contextStage=await saveStage(runId,"research_context",context,WorkflowStepId.RESEARCHER);
    }
    const deterministicVerification=context.deterministic_verification,deterministicChecks=context.deterministic_checks||[],dapHint=context.dap_hint||null,hintProtocol=dapHintProtocol(dapHint),localRecords=context.local_records||[],localIds=context.local_ids||[],scoutJson=context.scout_json||[],scoutToolEvidence=context.scout_tool_evidence||[],knownKnowledge=context.known_knowledge||[],knowledgeRecords=context.knowledge_records||[],official=context.official||[],evidenceGap=Boolean(context.evidence_gap),evidenceStatus=context.evidence_status,officialRecords=context.official_records||[],researchBase=context.research_base||[];
    let research=null,researchJson=null,researchToolEvidence=[],researchContinuation=null;
    if(durable){
      const inputBindingDigest=contentHash({run_id:runId,input_manifest_digest:inputRecord.payload_digest,research_context_digest:contextStage.record.payload_digest,repo_snapshot_id:context.repo_snapshot_id});
      await setCursor(runId,WorkflowStepId.RESEARCHER,StepPhase.RUNNING,{stepInputRef:contextStage.path});
      researchContinuation=await runResearcherContinuation({authority,runId,repoSnapshotId:context.repo_snapshot_id,inputManifestRef,inputBindingDigest,executeWorkUnit:async(args)=>{const {unit,restoredResults,roleExecutionId,attemptId}=args;await recoveryHooks?.beforeResearcherWorkUnit?.(args);
        let answer;if(unit.work_unit_id==="researcher.A")answer={payload:{localEvidence:evidencePromptView(localRecords),scouts:scoutJson,scout_tool_evidence:evidencePromptView(scoutToolEvidence)},evidence_refs:mergeEvidenceIds(localIds,scoutToolEvidence.map(x=>x.evidence_id))};
        else if(unit.work_unit_id==="researcher.B")answer={payload:{knownKnowledge:evidencePromptView(knowledgeRecords)},evidence_refs:evidenceIds(knowledgeRecords)};
        else if(unit.work_unit_id==="researcher.C")answer={payload:{official:evidencePromptView(officialRecords),evidence_gap:evidenceGap,evidence_status:evidenceStatus,evidence_gap_scope:"official_evidence_search"},evidence_refs:evidenceIds(officialRecords)};
        else if(unit.work_unit_id==="researcher.D")answer={payload:{A:restoredResults["researcher.A"]?.payload||null,B:restoredResults["researcher.B"]?.payload||null,C:restoredResults["researcher.C"]?.payload||null},evidence_refs:researchBase};
        else if(unit.work_unit_id==="researcher.E"){const assembled=restoredResults["researcher.D"]?.payload||{},durableHooks=createDurableToolEffectHooks({authority,runId,roleExecutionId,attemptId,workUnitId:unit.work_unit_id,inputBindingDigest,repoSnapshotId:context.repo_snapshot_id});research=await callReadOnlyRole("researcher",{system:["Researcher. Select decisive evidence. Return JSON only with exactly these top-level keys: research_status, answer, evidence_refs, rejected_source_refs, contradictions, bound_version. research_status must be SUPPORTED, CONTRADICTORY_EVIDENCE, or INSUFFICIENT_EVIDENCE. Keep answer under 120 characters; use at most 3 short strings per array; target under 100 tokens. Use only registered evidence IDs. If evidence_gap is true, do not treat official evidence as confirmed; local evidence remains available and must be evaluated on its own merits.",hintProtocol].filter(Boolean).join("\n"),user:JSON.stringify({task:rawRequest,failure,dap_hint:dapHint,...(assembled.A||{}),...(assembled.B||{}),...(assembled.C||{})})},toolRuntime,{baseEvidenceIds:researchBase,durableHooks});const payload=roleOutput(research,"researcher"),tools=toolEvidenceRecords(research),effectRefs=[...(research?.tool_loop?.continuation_state?.completed_effect_ids||[])];answer={payload,evidence_refs:mergeEvidenceIds(researchBase,tools.map(x=>x.evidence_id)),effect_refs:effectRefs,validation_summary:"Validated by existing researcher role-output contract"};}
        else throw new Error(`RESEARCHER_WORK_UNIT_UNKNOWN:${unit.work_unit_id}`);await recoveryHooks?.afterResearcherWorkUnit?.({...args,result:answer});return answer;}});
      researchJson=researchContinuation.payload;researchToolEvidence=durableResearchEvidence(researchContinuation.final_role_result);await setCursor(runId,WorkflowStepId.DIAGNOSER,StepPhase.PENDING,{activeRoleExecutionId:null});
    }else{research=await callReadOnlyRole("researcher",{system:["Researcher. Select decisive evidence. Return JSON only with exactly these top-level keys: research_status, answer, evidence_refs, rejected_source_refs, contradictions, bound_version. research_status must be SUPPORTED, CONTRADICTORY_EVIDENCE, or INSUFFICIENT_EVIDENCE. Keep answer under 120 characters; use at most 3 short strings per array; target under 100 tokens. Use only registered evidence IDs. If evidence_gap is true, do not treat official evidence as confirmed; local evidence remains available and must be evaluated on its own merits.",hintProtocol].filter(Boolean).join("\n"),user:JSON.stringify({task:rawRequest,failure,localEvidence:evidencePromptView(localRecords),dap_hint:dapHint,scouts:scoutJson,scout_tool_evidence:evidencePromptView(scoutToolEvidence),knownKnowledge:evidencePromptView(knowledgeRecords),official:evidencePromptView(officialRecords),evidence_gap:evidenceGap,evidence_status:evidenceStatus,evidence_gap_scope:"official_evidence_search"})},toolRuntime,{baseEvidenceIds:researchBase});researchJson=roleOutput(research,"researcher");researchToolEvidence=toolEvidenceRecords(research);}
    const diagnosisBase=mergeEvidenceIds(researchBase,researchContinuation?.final_role_result?.evidence_refs||[],researchToolEvidence.map(x=>x.evidence_id));let diagnosisStage=durable?loadStageRef(runId,"diagnosis"):null,diagnosisJson,diagnosisToolEvidence,diagnosisAudit;
    if(diagnosisStage){diagnosisJson=diagnosisStage.payload.diagnosis;diagnosisToolEvidence=diagnosisStage.payload.tool_evidence||[];diagnosisAudit=diagnosisStage.payload.tool_audit||null;}
    else{if(durable)await setCursor(runId,WorkflowStepId.DIAGNOSER,StepPhase.RUNNING);const handoff=researchContinuation?buildDownstreamInputBundle({roleResult:researchContinuation.final_role_result,roleContractVersion:ROLE_CONTRACT_VERSION,workflowVersion:1,workflowIteration:0,repoSnapshotId:context.repo_snapshot_id,upstreamResultDigests:[],toolContractVersions:[TOOL_CONTRACT_VERSION],evidencePolicyVersion:"debugai.evidence-registry/v1",budgetPolicyVersion:"debugai.default-budget/v1"}):null;const diagnosis=await callReadOnlyRole("diagnoser",{system:["Diagnoser. Produce a falsifiable diagnosis as one compact JSON object under 600 tokens, with at most 3 items per array and no prose outside JSON. Preserve uncertainty about official evidence when evidence_gap is true, but do not discard supplied local evidence.",hintProtocol].filter(Boolean).join("\n"),user:JSON.stringify({task:rawRequest,failure,localEvidence:evidencePromptView(localRecords),dap_hint:dapHint,research:researchJson,researcher_role_result:handoff,research_tool_evidence:evidencePromptView(researchToolEvidence),knownKnowledge:evidencePromptView(knowledgeRecords),official:evidencePromptView(officialRecords),evidence_gap:evidenceGap,evidence_status:evidenceStatus,evidence_gap_scope:"official_evidence_search"})},toolRuntime,{baseEvidenceIds:diagnosisBase});diagnosisJson=roleOutput(diagnosis,"diagnoser");diagnosisToolEvidence=toolEvidenceRecords(diagnosis);diagnosisAudit=toolAudit(diagnosis);if(durable)diagnosisStage=await saveStage(runId,"diagnosis",{diagnosis:diagnosisJson,tool_evidence:diagnosisToolEvidence,tool_audit:diagnosisAudit,research_role_result_id:researchContinuation.final_role_result.role_result_id},WorkflowStepId.EXTERNAL_REVIEW);}
    const localPublic=publicLocalEvidence(localEvidence),hypothesis={privacy_class:"PUBLIC",sanitized:true,opaque_evidence:true,statement:pickDiagnosisStatement(diagnosisJson),cause_class:String(diagnosisJson?.cause_kind||"UNKNOWN"),evidence_count:localEvidence.length+deterministicChecks.length+knownKnowledge.length+official.length,local_evidence_count:localPublic.length,local_evidence:localPublic,evidence_gap:evidenceGap,evidence_status:evidenceStatus,evidence_gap_scope:evidenceGap?"official_evidence_search":null};
    let externalStage=durable?loadStageRef(runId,"external_review"):null,external;if(externalStage)external=externalStage.payload.external;else{if(durable)await setCursor(runId,WorkflowStepId.EXTERNAL_REVIEW,StepPhase.RUNNING);external=externalReview?await externalReview.hypothesis({privacy:{privacy_class:"PUBLIC",sanitized:true,opaque_evidence:true},hypothesis}):null;if(durable)externalStage=await saveStage(runId,"external_review",{external},WorkflowStepId.FINAL_ANALYSIS);}
    const researcherAudit=research?toolAudit(research):researchContinuation?{durable_reuse:researchContinuation.reused_complete,role_execution_id:researchContinuation.role_execution_id,attempt_no:researchContinuation.attempt_no,executed_work_units:researchContinuation.executed_work_units}:null,tool_audit={code_scout:context.scout_tool_audit?.code_scout||null,causal_scout:context.scout_tool_audit?.causal_scout||null,researcher:researcherAudit,diagnoser:diagnosisAudit};
    const evidence_registry=registrySummary({local:localRecords,knowledge:knowledgeRecords,official:officialRecords});evidence_registry.tool_evidence_ids=mergeEvidenceIds(scoutToolEvidence.map(x=>x.evidence_id),researchToolEvidence.map(x=>x.evidence_id),diagnosisToolEvidence.map(x=>x.evidence_id));evidence_registry.total_with_tools=evidence_registry.total+evidence_registry.tool_evidence_ids.length;
    const result={run_id:runId,resumed:resuming,durable_researcher:researchContinuation?{role_execution_id:researchContinuation.role_execution_id,attempt_no:researchContinuation.attempt_no,reused_complete:researchContinuation.reused_complete,executed_work_units:researchContinuation.executed_work_units}:null,deterministic_verification:{status:deterministicVerification.status,checks:deterministicChecks},dap_hint:dapHint,scouts:scoutJson,known_knowledge:knownKnowledge,official_evidence:official,evidence_gap:evidenceGap,evidence_status:evidenceStatus,evidence_registry,research:researchJson,diagnosis:diagnosisJson,tool_audit,external_hypothesis_review:external,state:external?.json?.verdict==="PASS"?"HYPOTHESIS_APPROVED":"AWAITING_EXTERNAL_HYPOTHESIS_REVIEW"};
    runtimeEvidence?.write(runId,"analysis",result);await logRuntime({run_id:runId,severity:evidenceGap?"warn":"info",kind:"analysis",state:result.state,diagnosis:result.diagnosis,known_knowledge_count:knownKnowledge.length,official_evidence_count:official.length,evidence_registry_total:evidence_registry.total_with_tools,dap_hint_status:dapHint?.status||"NOT_CONFIGURED",evidence_gap:evidenceGap,evidence_status:evidenceStatus,deterministic_check_count:deterministicChecks.length,tool_calls:Object.values(tool_audit).reduce((n,x)=>n+(x?.total_calls||0),0)});if(durable)await setCursor(runId,WorkflowStepId.FINAL_ANALYSIS,StepPhase.DONE,{stepResultRef:externalStage?.path||diagnosisStage?.path||null,jobStatus:"DONE"});return result;
  }
  async function executePrepared(prepared){const existing=activeRuns.get(prepared.runId);if(existing)return existing.promise;const promise=(async()=>{try{const result=await executeAnalysis(prepared);backgroundErrors.delete(prepared.runId);return result;}catch(error){backgroundErrors.set(prepared.runId,String(error?.code||error?.message||error));try{await recordExecutionFailure(prepared.runId,error);}catch(markError){error.recovery_mark_error=String(markError?.code||markError?.message||markError);}throw error;}finally{activeRuns.delete(prepared.runId);}})();activeRuns.set(prepared.runId,{promise,started_at:Date.now()});return promise;}
  async function runAnalysis(input={}){return executePrepared(await prepareAnalysis(input));}
  async function startAnalysis(input={}){const prepared=await prepareAnalysis(input),duplicate=activeRuns.has(prepared.runId);void executePrepared(prepared).catch(()=>{});return{schema:"debugai.run-accepted/v1",run_id:prepared.runId,state:duplicate?"ALREADY_RUNNING":"RUNNING",resumed:prepared.resuming,duplicate_resume_suppressed:duplicate};}
  async function resumeAnalysis({runId}={}){if(typeof runId!=="string"||!runId)throw new Error("RUN_ID_REQUIRED");return startAnalysis({runId});}
  async function recoverStartup({awaitCompletion=false}={}){if(!authority?.durableEnabled?.())return{schema:"debugai.startup-recovery/v1",claimed:[],terminal:[],incompatible:[],completed:[]};const scan=authority.inspectDurableRuns(),claimed=[],scheduled=[];for(const item of scan.recoverable){let owned=false;try{await authority.claimRecoverableRun(item.run_id);owned=true;const prepared=await prepareAnalysis({runId:item.run_id});claimed.push(item.run_id);scheduled.push(executePrepared(prepared));}catch(error){if(owned)try{await recordExecutionFailure(item.run_id,error);}catch{}scan.incompatible.push({run_id:item.run_id,error:String(error?.code||error?.message||error)});}}const completed=awaitCompletion?await Promise.allSettled(scheduled):[];if(!awaitCompletion)for(const promise of scheduled)void promise.catch(()=>{});return{schema:"debugai.startup-recovery/v1",claimed,terminal:scan.terminal.map(x=>({run_id:x.run_id,reason:x.reason})),incompatible:scan.incompatible,completed:completed.map((x,index)=>({run_id:claimed[index],status:x.status,error:x.status==="rejected"?String(x.reason?.message||x.reason):null}))};}
  async function patchCandidate({runId,analysis,repo,selectedPaths,context,task}){const verdict=analysis?.external_hypothesis_review?.json?.verdict||analysis?.external_review?.verdict;if(verdict!=="PASS")throw new Error("PATCH_REQUIRES_EXTERNAL_HYPOTHESIS_REVIEW_PASS");const targetRepo=repoPolicy?repoPolicy.assertRepo(repo):repo,source=patchPacketSource(targetRepo,selectedPaths),inventory=verificationInventory(targetRepo),patchPacket=makePatchPacket({runId,diagnosisRef:`diagnosis_${contentHash(analysis?.diagnosis||{})}`,repositoryRevision:repositorySnapshot(targetRepo),paths:selectedPaths,sourceExcerpts:source.sourceExcerpts,preconditionHashes:source.preconditionHashes,reproductionSummary:{status:String(analysis?.deterministic_verification?.status||"UNKNOWN"),checks:analysis?.deterministic_verification?.checks||[]},testInventory:inventory.checks,invariants:[{name:"candidate-only-patch-engineer",status:"PASS"},{name:"master-approval-required",status:"PASS"}],prohibitedPaths:source.prohibitedPaths,evidenceRefs:patchPacketEvidenceRefs(analysis)});runtimeEvidence?.write(runId,"patch_packet",patchPacket);const out=await callReadOnlyRole("patch_engineer",{system:"Patch Engineer. Candidate only. Never apply. JSON only.",user:JSON.stringify({patch_packet:patchPacket,diagnosis:analysis.diagnosis,context,task})},makeReadOnlyToolRuntime(targetRepo),{baseEvidenceIds:patchPacketEvidenceRefs(analysis),strictEvidenceRefs:true});const candidateResult=roleOutput(out,"patch_engineer");const candidate=patchService?patchService.create({repo:targetRepo,selectedPaths,task,result:candidateResult}):candidateResult;if(authority){let run=authority.load(runId);run=authority.transition(run,"PATCH_READY");authority.transition(run,"WAITING_APPROVAL");}runtimeEvidence?.write(runId,"patch_candidate",{id:candidate.id,diff_hash:candidate.diff_hash,summary:candidate.summary,patch_packet_digest:patchPacket.packet_digest});await logRuntime({run_id:runId,severity:"info",kind:"patch_candidate",candidate_id:candidate.id,diff_hash:candidate.diff_hash,patch_packet_digest:patchPacket.packet_digest,summary:candidate.summary,state:"WAITING_MASTER_APPROVAL"});return{run_id:runId,state:"WAITING_MASTER_APPROVAL",candidate,patch_packet:{schema:patchPacket.schema,packet_digest:patchPacket.packet_digest}};}
  async function approveAndVerify({runId,candidateId,candidateHash,decision,repo}){
    if(!patchService)throw new Error("PATCH_SERVICE_REQUIRED");
    let run=null;if(authority)run=authority.load(runId);
    if(decision!=="approve"){if(authority)authority.transition(run,"BLOCKED");throw new Error("PATCH_APPROVAL_REQUIRED");}
    if(authority)run=authority.transition(run,"APPLYING");
    let out;try{out=patchService.apply({candidateId,candidateHash,decision,repo});}catch(e){if(authority){try{authority.transition(run,"BLOCKED");}catch{}}throw e;}
    if(authority)run=authority.transition(run,"RETESTING");
    const targetRepo=out?.candidate?.repo||repo||null;
    const postApplyRepositoryRevision=targetRepo?repositorySnapshot(targetRepo):null;
    runtimeEvidence?.write(runId,"verification",{checks:out.checks,invariants:out.invariants,gates:out.gates,pass:out.pass,post_apply_repository_revision:postApplyRepositoryRevision});
    await logRuntime({run_id:runId,severity:out.pass?"info":"error",kind:"verification",pass:out.pass,checks:out.checks,invariants:out.invariants,gates:out.gates,post_apply_repository_revision:postApplyRepositoryRevision});
    if(!out.pass){if(authority)authority.transition(run,"FAILED");return{run_id:runId,state:"FAILED_RETEST",...out};}
    const verificationRecords=registerEvidenceList("LOCAL_RUNTIME",[...(out.checks||[]),{kind:"invariants",value:out.invariants},{kind:"gates",value:out.gates}]),verificationIds=evidenceIds(verificationRecords),executedTests=(out.checks||[]).filter(check=>check?.executed===true),receipt=out?.applied?.receipt||null;
    const reviewPacket=makeReviewPacket({candidateRef:candidateId,applyReceiptRef:String(receipt?.transaction_id||receipt?.candidate_id||""),repositoryRevision:postApplyRepositoryRevision,changedPaths:out?.candidate?.files||[],diff:out?.candidate?.diff||"",prePostHashes:reviewPacketHashes(out?.candidate,receipt),executedTests,testResults:out.checks||[],invariants:reviewPacketInvariants(out),evidenceRefs:verificationIds});
    runtimeEvidence?.write(runId,"review_packet",reviewPacket);
    const lr=await runRoleWithReadOnlyTools({aiCore,role:"local_reviewer",system:"Local Reviewer. Review the local Review Packet from fresh context. JSON only.",user:JSON.stringify({review_packet:reviewPacket}),toolRuntime:makeReadOnlyToolRuntime(targetRepo),baseEvidenceIds:verificationIds,strictEvidenceRefs:true});
    const local_review=roleOutput(lr,"local_reviewer");
    const publicReviewSummary=publicReviewPacketSummary(reviewPacket,{localVerdict:local_review.verdict||"UNKNOWN"});
    let final=null;if(externalReview)final=await externalReview.final({privacy:{privacy_class:"PUBLIC",sanitized:true,opaque_evidence:true},summary:publicReviewSummary});
    const currentRepositoryRevision=targetRepo?repositorySnapshot(targetRepo):null;
    const analysisEvidenceRecord=runtimeEvidence?.list?.(runId,{types:["analysis"],limit:1})?.[0]||null;
    const completion_gate=evaluateCompletionGate(buildCompletionGateInput({runId,runState:run?.state||"RETESTING",candidateId,candidateHash,decision,patchResult:out,postApplyRepositoryRevision,currentRepositoryRevision,localReview:local_review,externalFinal:final,analysisEvidenceRecord}));
    runtimeEvidence?.write(runId,"completion_gate",completion_gate);
    const externalPass=String(final?.json?.verdict||"").toUpperCase()==="PASS",complete=completion_gate.complete;
    if(authority&&complete)run=authority.transition(run,"COMPLETE");
    else if(authority&&externalPass&&!complete)run=authority.transition(run,"BLOCKED");
    const state=complete?"COMPLETE":externalPass?"BLOCKED_COMPLETION_GATE":"AWAITING_EXTERNAL_FINAL_REVIEW";
    await logRuntime({run_id:runId,severity:complete?"info":"warn",kind:"final_review",state,local_verdict:local_review.verdict||"UNKNOWN",external_verdict:final?.json?.verdict||"PENDING",completion_gate});
    return{run_id:runId,state,...out,local_review,review_packet:{schema:reviewPacket.schema,packet_digest:reviewPacket.packet_digest},external_final_review:final,completion_gate,post_apply_repository_revision:postApplyRepositoryRevision,current_repository_revision:currentRepositoryRevision};
  }
  function resolveVerificationRepo(repo){if(!repoPolicy)throw new Error("VERIFY_REPO_POLICY_REQUIRED");return repoPolicy.assertRepo(repo);}
  function verificationScope(repo,selectedPaths){const paths=[...new Set((Array.isArray(selectedPaths)?selectedPaths:[]).map(String).filter(Boolean))];const files=paths.map(rel=>{const item=readText(repo,rel,{maxChars:1});return{path:item.path,sha256:item.sha256,size:item.size};});return{mode:files.length?"FILES":"REPOSITORY",files};}
  function verificationInventory(repo){try{return testInventory(repo);}catch(error){if(String(error?.message||error).includes("READ_FILE_NOT_FOUND:package.json"))return{package_json:null,package_manager:null,checks:[]};throw error;}}
  function verificationVerdict(deterministic,localReview,localReviewError){const checks=Array.isArray(deterministic?.checks)?deterministic.checks:[];if(deterministic?.status!=="FINAL_VALID"||checks.length===0)return"INSUFFICIENT_EVIDENCE";if(checks.some(check=>check.status==="FAIL"))return"FAIL";const local=String(localReview?.verdict||localReview?.decision||"").toUpperCase();if(local==="FAIL"||local==="REJECTED"||local==="BLOCKED")return"FAIL";if(localReviewError||!checks.every(check=>check.status==="PASS"))return"UNKNOWN";if(local==="PASS"||local==="APPROVED"||local==="ACCEPTED")return"PASS";return"UNKNOWN";}
  async function verifyReadOnly({repo,selectedPaths=[],changeScope=[],task=""}={}){if(!sandboxVerification)throw new Error("SANDBOX_VERIFICATION_REQUIRED");const targetRepo=resolveVerificationRepo(repo),verificationId=`verify_${crypto.randomUUID()}`;const scopeBefore=verificationScope(targetRepo,selectedPaths),inventory=verificationInventory(targetRepo);const deterministic=await sandboxVerification.collect(targetRepo),scopeAfter=verificationScope(targetRepo,selectedPaths);const changed=scopeBefore.files.filter((file,index)=>scopeAfter.files[index]?.sha256!==file.sha256).map(file=>file.path);const invariants={pass:changed.length===0,failures:changed.map(file=>`SOURCE_MUTATED:${file}`),checked_paths:scopeBefore.files.length,checked_receipts:0,authority:"READ_ONLY_SOURCE_IMMUTABILITY"};const reviewerChecks=deterministic.checks.map(reviewableVerificationCheck);const records=registerEvidenceList("LOCAL_RUNTIME",[...reviewerChecks,{kind:"test_inventory",value:inventory},{kind:"file_change_scope",value:{selected_paths:scopeBefore.files.map(x=>x.path),change_scope:Array.isArray(changeScope)?changeScope.map(String):[],task:String(task||"")}},{kind:"invariants",value:invariants}]),ids=evidenceIds(records);let local_review=null,local_review_error=null;try{const review=await runRoleWithReadOnlyTools({aiCore,role:"local_reviewer",system:"Local Reviewer. Review read-only deterministic verification from fresh context. JSON only. Never claim patch application.",user:JSON.stringify({verification_evidence:records}),toolRuntime:makeReadOnlyToolRuntime(targetRepo),baseEvidenceIds:ids,strictEvidenceRefs:true});local_review=roleOutput(review,"local_reviewer");}catch(error){local_review_error=String(error?.code||error?.message||"LOCAL_REVIEW_UNAVAILABLE").split(":")[0];}const verdict=verificationVerdict(deterministic,local_review,local_review_error),result={schema:"debugai.verify-result/v1",verification_id:verificationId,read_only:true,patch_applied:false,repo:targetRepo,scope:{mode:scopeBefore.mode,files:scopeBefore.files,change_scope:Array.isArray(changeScope)?changeScope.map(String):[]},test_inventory:inventory,deterministic_verification:deterministic,invariants,local_review,local_review_error,verdict};runtimeEvidence?.write(verificationId,"read_only_verification",result);await logRuntime({run_id:verificationId,severity:verdict==="PASS"?"info":verdict==="FAIL"?"error":"warn",kind:"read_only_verification",verdict,check_count:deterministic.checks.length,patch_applied:false});return result;}
  function durableStatus(runId){if(!authority?.durableEnabled?.())return null;try{const {state,manifest}=authority.loadDurable(runId);return{generation:state.generation,execution_epoch:state.execution_epoch,job_status:state.job_status,active_in_process:activeRuns.has(runId),last_execution_error:backgroundErrors.get(runId)||null,workflow_cursor:manifest.workflow_cursor,role_executions:Object.fromEntries(Object.entries(manifest.role_execution_refs||{}).map(([id,ref])=>[id,{role:ref.role,status:ref.status,attempt_no:ref.attempt_no,latest_checkpoint_ref:ref.latest_checkpoint_ref||null,final_role_result_ref:ref.final_role_result_ref||null}]))};}catch(error){if(String(error?.message||error).includes("DURABLE_RECORD_NOT_FOUND")||String(error?.message||error).includes("ENOENT"))return null;throw error;}}
  function status(runId){if(!authority)throw new Error("RUN_AUTHORITY_REQUIRED");const run=authority.load(runId);return{schema:"debugai.run-status/v1",run_id:run.run_id,state:run.state,project_id:run.project_id,project_dir:run.project_dir,created_at:run.created_at,updated_at:run.updated_at,durable:durableStatus(runId)};}
  function inspect(runId){const run=status(runId),durable=run.durable;if(!runtimeEvidence)return{schema:"debugai.run-inspection/v1",run,durable,artifacts:{}};const records=runtimeEvidence.list(runId,{types:["analysis","patch_packet","patch_candidate","verification","review_packet","completion_gate"],limit:16}),artifacts={};for(const record of records)if(!artifacts[record.type])artifacts[record.type]=record;return{schema:"debugai.run-inspection/v1",run,durable,artifacts};}
  async function promote(asset){assertPromotable(asset);if(!tgserver)throw new Error("TGSERVER_ADAPTER_REQUIRED");return tgserver.promote(asset);}
  async function searchKnowledge(query,opts={}){if(!tgserver)throw new Error("TGSERVER_ADAPTER_REQUIRED");return tgserver.search(query,opts);}
  return{runAnalysis,startAnalysis,resumeAnalysis,recoverStartup,patchCandidate,approveAndVerify,verifyReadOnly,status,inspect,promote,searchKnowledge};
}
module.exports={createWorkflow,parseJson,roleOutput,toolEvidenceRecords,toolAudit,pickDiagnosisStatement,publicLocalEvidence,dapFailureChecks,activeDapHint,dapHintProtocol,reviewStreamEvidence,reviewableVerificationCheck,evidencePromptView,repositorySnapshotId};
