"use strict";
const crypto=require("node:crypto");
const {assertPromotable}=require("./asset-promotion.js");
const EXTERNAL_EVIDENCE_CATEGORIES=new Set(["DEPENDENCY","API","VERSION","KNOWN_BUG","CVE","SPECIFICATION_CONFLICT","SPEC_CONFLICT"]);
function parseJson(c){if(typeof c!=="string")return c;return JSON.parse(c.trim().replace(/^```json\s*/i,"").replace(/```$/i,"").trim());}
function localEvidenceSufficient(localEvidence=[]){return localEvidence.some(x=>x&&typeof x==="object"&&(x.sufficient_for_attribution===true||x.root_cause_confirmed===true||String(x.status||"").toUpperCase()==="CONFIRMED_CAUSE"));}
function shouldSearchExternalEvidence({failure,localEvidence=[]}={}){if(failure?.evidence_gap===true||failure?.external_evidence_required===true)return true;if(localEvidenceSufficient(localEvidence))return false;const category=String(failure?.category||failure?.cause_class||failure?.kind||"").trim().toUpperCase().replace(/[ -]+/g,"_");return EXTERNAL_EVIDENCE_CATEGORIES.has(category);}
function createWorkflow({aiCore,externalReview=null,evidenceSearch=null,runtimeEvidence=null,tgserver=null,patchService=null,authority=null}={}){
 if(!aiCore)throw new Error("AI_CORE_ADAPTER_REQUIRED");
 async function telemetry(stream,eventType,runId,payload,severity="info"){if(!tgserver)return null;if(typeof tgserver.emit==="function")return tgserver.emit({stream,eventType,runId,payload,severity});if(typeof tgserver.log==="function")return tgserver.log({stream,event_type:eventType,run_id:runId,payload,severity});return null;}
 async function runAnalysis({runId=null,rawRequest="",failure,localEvidence=[],repo=null,projectId=null}={}){
  let authRun=null;if(authority){authRun=authority.start({rawRequest,repo,projectId});runId=authRun.run_id;authority.transition(authRun,"PARSED");authority.transition(authRun,"CONTEXT_READY");authority.transition(authRun,"VERIFYING");authority.transition(authRun,"FAILED");authority.transition(authRun,"RESOLVING");}
  runId=runId||crypto.randomUUID();runtimeEvidence?.write(runId,"failure",failure);await telemetry("EVIDENCE","FAILURE_OBSERVED",runId,{failure,local_evidence_count:localEvidence.length},"error");
  const query=String(failure?.message||failure?.summary||"debug failure"),searchRequired=shouldSearchExternalEvidence({failure,localEvidence});
  const [scouts,knownKnowledge,searchResult]=await Promise.all([
   Promise.all([aiCore.call("code_scout",{system:"Code Scout. JSON only.",user:JSON.stringify({failure,evidence:localEvidence})}),aiCore.call("causal_scout",{system:"Causal Scout. JSON only.",user:JSON.stringify({failure,evidence:localEvidence})})]),
   tgserver?tgserver.search(query):Promise.resolve([]),
   searchRequired&&evidenceSearch?evidenceSearch.search({query,context:JSON.stringify({category:failure?.category||failure?.cause_class||failure?.kind||null}),requestId:`${runId}-evidence`}):Promise.resolve({performed:false,status:searchRequired?"UNAVAILABLE":"NOT_REQUIRED",evidence:[],evidence_registry:null,evidence_bindings:null})
  ]);
  const official=Array.isArray(searchResult?.evidence)?searchResult.evidence:[];
  await telemetry("EVIDENCE","EVIDENCE_COLLECTION_COMPLETE",runId,{local_evidence_count:localEvidence.length,known_knowledge_count:knownKnowledge.length,external_search_required:searchRequired,external_search_status:searchResult?.status||"UNKNOWN",official_evidence_count:official.length,evidence_registry_hash:searchResult?.evidence_registry?.registry_hash||null,evidence_bindings_hash:searchResult?.evidence_bindings?.bindings_hash||null},"info");
  const research=await aiCore.call("researcher",{system:"Researcher. Select decisive evidence. JSON only.",user:JSON.stringify({failure,localEvidence,scouts:scouts.map(x=>parseJson(x.content)),knownKnowledge,official})});
  const diagnosis=await aiCore.call("diagnoser",{system:"Diagnoser. Produce falsifiable diagnosis. JSON only.",user:JSON.stringify({failure,research:parseJson(research.content),knownKnowledge})});const diagnosisJson=parseJson(diagnosis.content);
  const hypothesis={privacy_class:"PUBLIC",sanitized:true,opaque_evidence:true,statement:String(diagnosisJson?.public_statement||"behavioral mismatch"),cause_class:String(diagnosisJson?.cause_kind||"UNKNOWN"),evidence_count:localEvidence.length+knownKnowledge.length+official.length};
  let external=null;if(externalReview)external=await externalReview.hypothesis({privacy:{privacy_class:"PUBLIC",sanitized:true,opaque_evidence:true},hypothesis});
  const result={run_id:runId,scouts:scouts.map(x=>parseJson(x.content)),known_knowledge:knownKnowledge,official_evidence:official,evidence_search:{performed:searchResult?.performed===true,required:searchRequired,status:searchResult?.status||"UNKNOWN",evidence_registry:searchResult?.evidence_registry||null,evidence_bindings:searchResult?.evidence_bindings||null},research:parseJson(research.content),diagnosis:diagnosisJson,external_hypothesis_review:external,state:external?.json?.verdict==="PASS"?"HYPOTHESIS_APPROVED":"AWAITING_EXTERNAL_HYPOTHESIS_REVIEW"};
  runtimeEvidence?.write(runId,"analysis",result);await telemetry("TRACE","ANALYSIS_COMPLETE",runId,{state:result.state,evidence_count:hypothesis.evidence_count,external_review_verdict:external?.json?.verdict||null},"debug");return result;
 }
 async function patchCandidate({runId,analysis,repo,selectedPaths,context,task}){const verdict=analysis?.external_hypothesis_review?.json?.verdict||analysis?.external_review?.verdict;if(verdict!=="PASS")throw new Error("PATCH_REQUIRES_EXTERNAL_HYPOTHESIS_REVIEW_PASS");const out=await aiCore.call("patch_engineer",{system:"Patch Engineer. Candidate only. Never apply. JSON only.",user:JSON.stringify({diagnosis:analysis.diagnosis,context,task})});const candidateResult=parseJson(out.content),candidate=patchService?patchService.create({repo,selectedPaths,task,result:candidateResult}):candidateResult;if(authority){let run=authority.load(runId);run=authority.transition(run,"PATCH_READY");authority.transition(run,"WAITING_APPROVAL");}runtimeEvidence?.write(runId,"patch_candidate",{id:candidate.id,diff_hash:candidate.diff_hash,summary:candidate.summary});await telemetry("TRACE","PATCH_CANDIDATE",runId,{candidate_id:candidate.id,diff_hash:candidate.diff_hash,summary:candidate.summary},"info");return {run_id:runId,state:"WAITING_MASTER_APPROVAL",candidate};}
 async function approveAndVerify({runId,candidateId,candidateHash,decision,repo}){if(!patchService)throw new Error("PATCH_SERVICE_REQUIRED");let run=null;if(authority)run=authority.load(runId);if(decision!=="approve"){if(authority)authority.transition(run,"BLOCKED");await telemetry("RESULT","PATCH_NOT_APPROVED",runId,{candidate_id:candidateId},"warn");throw new Error("PATCH_APPROVAL_REQUIRED");}if(authority)run=authority.transition(run,"APPLYING");await telemetry("TRACE","PATCH_APPROVED",runId,{candidate_id:candidateId},"info");let out;try{out=patchService.apply({candidateId,candidateHash,decision,repo});}catch(e){if(authority){try{authority.transition(run,"BLOCKED");}catch{}}await telemetry("RESULT","PATCH_APPLY_FAILED",runId,{candidate_id:candidateId,error_code:e?.code||e?.name||"PATCH_APPLY_FAILED"},"error");throw e;}if(authority)run=authority.transition(run,"RETESTING");runtimeEvidence?.write(runId,"verification",{checks:out.checks,invariants:out.invariants,gates:out.gates,pass:out.pass});await telemetry("RESULT","DETERMINISTIC_VERIFICATION",runId,{pass:out.pass,checks:out.checks,invariants:out.invariants,gates:out.gates},out.pass?"info":"error");if(!out.pass){if(authority)authority.transition(run,"FAILED");return {run_id:runId,state:"FAILED_RETEST",...out};}const lr=await aiCore.call("local_reviewer",{system:"Local Reviewer. Review deterministic results. JSON only.",user:JSON.stringify({checks:out.checks,invariants:out.invariants,gates:out.gates})});const local_review=parseJson(lr.content);let final=null;if(externalReview)final=await externalReview.final({privacy:{privacy_class:"PUBLIC",sanitized:true,opaque_evidence:true},summary:{check_count:out.checks.length,invariants_pass:out.invariants.pass,local_verdict:local_review.verdict||"UNKNOWN"}});const complete=final?.json?.verdict==="PASS";if(authority&&complete)authority.transition(run,"COMPLETE");const state=complete?"COMPLETE":"AWAITING_EXTERNAL_FINAL_REVIEW";await telemetry("RESULT","FINAL_REVIEW",runId,{state,local_verdict:local_review.verdict||"UNKNOWN",external_verdict:final?.json?.verdict||"PENDING"},complete?"info":"warn");return {run_id:runId,state,...out,local_review,external_final_review:final};}
 async function promote(asset){assertPromotable(asset);if(!tgserver)throw new Error("TGSERVER_ADAPTER_REQUIRED");return tgserver.promote(asset);}
 async function searchKnowledge(query,opts={}){if(!tgserver)throw new Error("TGSERVER_ADAPTER_REQUIRED");return tgserver.search(query,opts);}
 return {runAnalysis,patchCandidate,approveAndVerify,promote,searchKnowledge};
}
module.exports={EXTERNAL_EVIDENCE_CATEGORIES,localEvidenceSufficient,shouldSearchExternalEvidence,createWorkflow};
