"use strict";
const crypto=require("node:crypto"),fs=require("node:fs");
const {stableStringify,sha256}=require("../deterministic-json.js");
class EvidenceSearchError extends Error{constructor(code,msg,meta={}){super(msg);this.code=code;this.meta=meta;}}
function loadSharedKey({sharedKey,sharedKeyFile}={}){let v=sharedKey;if(!v&&sharedKeyFile)v=fs.readFileSync(sharedKeyFile);if(!v&&process.env.DEBUG_AI_EVIDENCE_SEARCH_SHARED_KEY_FILE)v=fs.readFileSync(process.env.DEBUG_AI_EVIDENCE_SEARCH_SHARED_KEY_FILE);if(!v)v=process.env.DEBUG_AI_EVIDENCE_SEARCH_SHARED_KEY;const b=Buffer.isBuffer(v)?v:Buffer.from(String(v||""),"utf8");if(b.length<32)throw new EvidenceSearchError("EVIDENCE_SEARCH_SHARED_KEY_INVALID","Evidence Search shared key must be at least 32 bytes");return b;}
function sign({body,key,service,callerId,requestId,now=Date.now(),ttlMs=60000,nonce=crypto.randomUUID()}){const bodyHash=sha256(Buffer.isBuffer(body)?body:Buffer.from(String(body),"utf8"));const fields={service:String(service),caller_id:String(callerId),request_id:String(requestId),issued_at:new Date(now).toISOString(),expires_at:new Date(now+ttlMs).toISOString(),nonce:String(nonce),body_sha256:bodyHash};const sig=crypto.createHmac("sha256",key).update(stableStringify(fields)).digest("hex");return {"x-astera-service":fields.service,"x-astera-caller-id":fields.caller_id,"x-astera-request-id":fields.request_id,"x-astera-issued-at":fields.issued_at,"x-astera-expires-at":fields.expires_at,"x-astera-nonce":fields.nonce,"x-astera-body-sha256":fields.body_sha256,"x-astera-signature":sig};}
function verifyIndex(body){const reg=body?.evidence_registry,bind=body?.evidence_bindings;if(!reg||!bind)throw new EvidenceSearchError("EVIDENCE_SEARCH_PROVENANCE_MISSING","Evidence Search response lacks Registry/Bindings");if(reg.schema_version!=="astera.evidence-registry.v1"||!Array.isArray(reg.entries)||reg.registry_hash!==sha256(reg.entries))throw new EvidenceSearchError("EVIDENCE_SEARCH_REGISTRY_INVALID","Evidence Registry integrity failed");if(bind.schema_version!=="astera.evidence-bindings.v1"||!Array.isArray(bind.bindings)||bind.bindings_hash!==sha256(bind.bindings))throw new EvidenceSearchError("EVIDENCE_SEARCH_BINDINGS_INVALID","Evidence Bindings integrity failed");return {registry:reg,bindings:bind};}
function createEvidenceSearchAdapter({baseUrl=process.env.DEBUG_AI_EVIDENCE_SEARCH_URL,sharedKey=null,sharedKeyFile=null,service=process.env.DEBUG_AI_EVIDENCE_SEARCH_SERVICE||"debug-ai",callerId=process.env.DEBUG_AI_EVIDENCE_SEARCH_CALLER_ID||"debug-ai",fetchImpl=globalThis.fetch,timeoutMs=30000}={}){
 if(!baseUrl)throw new EvidenceSearchError("EVIDENCE_SEARCH_URL_REQUIRED","DEBUG_AI_EVIDENCE_SEARCH_URL is required");if(typeof fetchImpl!=="function")throw new EvidenceSearchError("EVIDENCE_SEARCH_FETCH_REQUIRED","fetch is required");const key=loadSharedKey({sharedKey,sharedKeyFile});const endpoint=new URL("/internal/v1/evidence/search",baseUrl).toString();
 async function search({query,context="",limit=8,requestId=crypto.randomUUID()}={}){if(!String(query||"").trim())throw new EvidenceSearchError("QUERY_REQUIRED","query required");const payload={question:String(query).trim(),context:String(context||"").slice(0,32768),search:{free_projection:true,free_current:true,free_general_web:true},paid_search:{enabled:false},maximum_results:Math.max(1,Math.min(128,Number(limit)||8)),deadline_ms:Math.max(1000,Math.min(60000,timeoutMs))};const body=JSON.stringify(payload),headers=sign({body,key,service,callerId,requestId,ttlMs:Math.min(timeoutMs+5000,60000)}),ctl=new AbortController(),timer=setTimeout(()=>ctl.abort(),timeoutMs);try{const r=await fetchImpl(endpoint,{method:"POST",headers:{"content-type":"application/json",...headers},body,signal:ctl.signal});const text=await r.text();let out;try{out=JSON.parse(text)}catch{throw new EvidenceSearchError("EVIDENCE_SEARCH_ENVELOPE","invalid JSON");}if(!r.ok)throw new EvidenceSearchError(out.code||"EVIDENCE_SEARCH_HTTP",`Evidence Search HTTP ${r.status}`,{status:r.status,body:out});if(out.ai_used!==false)throw new EvidenceSearchError("EVIDENCE_SEARCH_AI_BOUNDARY","Evidence Search must remain non-AI");if(out.status!=="FINAL_VALID")return {performed:true,status:String(out.status||"UNKNOWN"),evidence:[],evidence_registry:out.evidence_registry||null,evidence_bindings:out.evidence_bindings||null,coverage:out.coverage||null,result_hash:out.result_hash||null};const index=verifyIndex(out);return {performed:true,status:"FINAL_VALID",evidence:Array.isArray(out.evidence)?out.evidence:[],evidence_registry:index.registry,evidence_bindings:index.bindings,coverage:out.coverage||null,result_hash:out.result_hash||null};}catch(e){if(e?.name==="AbortError")throw new EvidenceSearchError("EVIDENCE_SEARCH_TIMEOUT","Evidence Search timed out");throw e;}finally{clearTimeout(timer);}}
 return {endpoint,service,search};
}
module.exports={EvidenceSearchError,createEvidenceSearchAdapter,sign,verifyIndex};
