"use strict";
const FORBIDDEN=/(?:[A-Za-z]:\\|\/(?:home|Users|mnt|etc|var|tmp|opt|srv)\/|Bearer\s+\S+|(?:api[_-]?key|secret|password|cookie|private[_-]?key|access[_-]?token|refresh[_-]?token)\s*[:=])/i;
function assertPublicOpaque(payload){const p=payload?.privacy||payload;if(String(p?.privacy_class)!=="PUBLIC"||p?.sanitized!==true||p?.opaque_evidence!==true)throw new Error("EXTERNAL_PRIVACY_METADATA_REQUIRED");if(FORBIDDEN.test(JSON.stringify(payload)))throw new Error("EXTERNAL_PRIVACY_BLOCK");return true;}
function createExternalReviewAdapter({groqKey=process.env.GROQ_API_KEY,geminiKey=process.env.GEMINI_API_KEY,fetchImpl=globalThis.fetch,groqUrl=process.env.DEBUG_AI_GROQ_URL||"https://api.groq.com/openai/v1/chat/completions",geminiUrl=process.env.DEBUG_AI_GEMINI_URL||"https://generativelanguage.googleapis.com/v1beta/openai/chat/completions",groqModel="openai/gpt-oss-20b",geminiModel="gemini-3.8-flash"}={}){
 async function one(provider,payload,kind){const cfg=provider==="groq"?{key:groqKey,url:groqUrl,model:groqModel}:{key:geminiKey,url:geminiUrl,model:geminiModel};if(!cfg.key)throw new Error(`${provider.toUpperCase()}_KEY_MISSING`);const r=await fetchImpl(cfg.url,{method:"POST",headers:{authorization:`Bearer ${cfg.key}`,"content-type":"application/json"},body:JSON.stringify({model:cfg.model,messages:[{role:"system",content:`Independent ${kind} reviewer. Return one JSON object only.`},{role:"user",content:JSON.stringify(payload)}],max_tokens:kind==="final"?900:650,stream:false})});const text=await r.text();if(!r.ok)throw new Error(`${provider.toUpperCase()}_HTTP_${r.status}`);let b=JSON.parse(text);let c=b?.choices?.[0]?.message?.content;if(typeof c!=="string")throw new Error("EXTERNAL_REVIEW_EMPTY");return {provider,model:cfg.model,json:JSON.parse(c.replace(/^```json\s*/i,"").replace(/```$/i,"").trim())};}
 async function review(kind,payload,{secondOpinion=false}={}){assertPublicOpaque(payload);const first=await one("groq",payload,kind);if(!secondOpinion&&first.json?.verdict==="PASS")return first;if(geminiKey){const second=await one("gemini",payload,kind);return {provider:`${first.provider}+${second.provider}`,primary:first,second_opinion:second,json:second.json?.verdict==="FAIL"?second.json:first.json};}return first;}
 return {hypothesis:(p,o)=>review("hypothesis",p,o),final:(p,o)=>review("final",p,o)};
}
module.exports={assertPublicOpaque,createExternalReviewAdapter};
