"use strict";
const fs=require("node:fs"),path=require("node:path"),crypto=require("node:crypto");
const {stableStringify,sha256}=require("../deterministic-json.js");
const FORBIDDEN=/(authorization|cookie|api[_-]?key|secret|password|private[_-]?key|access[_-]?token|refresh[_-]?token)/i;
const STREAMS=new Set(["EVIDENCE","TRACE","RESULT"]);
function redact(v){if(v==null)return v;if(typeof v==="string")return v.replace(/Bearer\s+\S+/gi,"Bearer [REDACTED]").replace(/(?:api[_-]?key|secret|password|token)\s*[:=]\s*\S+/gi,m=>m.split(/[:=]/)[0]+"=[REDACTED]");if(Array.isArray(v))return v.map(redact);if(typeof v==="object"){const o={};for(const [k,x] of Object.entries(v))o[k]=FORBIDDEN.test(k)?"[REDACTED]":redact(x);return o;}return v;}
function createTgserverAssetAdapter({baseUrl=process.env.DEBUG_AI_TGSERVER_URL,projectId=process.env.DEBUG_AI_TGSERVER_PROJECT_ID,fetchImpl=globalThis.fetch,outboxDir=process.env.DEBUG_AI_TGSERVER_OUTBOX_DIR||path.join(process.env.DEBUG_AI_RUNTIME_ROOT||"/app/runtime","tgserver-outbox"),timeoutMs=10000}={}){if(!baseUrl)throw new Error("TGSERVER_URL_REQUIRED");if(!projectId||!/^P\d+$/.test(String(projectId)))throw new Error("TGSERVER_PROJECT_ID_REQUIRED");if(typeof fetchImpl!=="function")throw new Error("TGSERVER_FETCH_REQUIRED");const endpoint=new URL("/ingest",baseUrl).toString();fs.mkdirSync(outboxDir,{recursive:true});
 function envelope({stream,eventType,runId,payload,severity="info",timestamp=new Date().toISOString()}){stream=String(stream||"").toUpperCase();if(!STREAMS.has(stream))throw new Error("TGSERVER_STREAM_INVALID");if(!String(eventType||"").trim())throw new Error("TGSERVER_EVENT_TYPE_REQUIRED");if(!String(runId||"").trim())throw new Error("TGSERVER_RUN_ID_REQUIRED");const safe=redact(payload);return {schema_version:"debug-ai.telemetry.v1",stream,event_type:String(eventType),run_id:String(runId),payload:safe,timestamp:new Date(timestamp).toISOString(),severity};}
 async function post(record){const body={project_id:String(projectId),severity:record.severity,message:stableStringify(record),hint:`${record.stream}:${record.event_type}`,timestamp:record.timestamp};const ctl=new AbortController(),timer=setTimeout(()=>ctl.abort(),timeoutMs);try{const r=await fetchImpl(endpoint,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body),signal:ctl.signal});const text=await r.text();let out;try{out=JSON.parse(text)}catch{out={status:"error",reason:text.slice(0,200)}}if(!r.ok||!["accepted","duplicate"].includes(out.status))throw new Error(`TGSERVER_INGEST_${r.status}:${out.reason||out.status||"unknown"}`);return out;}finally{clearTimeout(timer);}}
 function queue(record,error){const safe={...record,delivery:{status:"TELEMETRY_DEGRADED",error_code:String(error?.code||error?.name||"TGSERVER_UNAVAILABLE")}};const id=`${Date.now()}-${sha256(safe).slice(0,24)}.json`;const file=path.join(outboxDir,id);fs.writeFileSync(file,stableStringify(safe)+"\n",{flag:"wx",mode:0o600});return file;}
 async function emit(input){const record=envelope(input);try{const receipt=await post(record);return {status:"DELIVERED",receipt,record_hash:sha256(record)};}catch(error){const outbox_path=queue(record,error);return {status:"TELEMETRY_DEGRADED",outbox_path,record_hash:sha256(record)};}}
 async function promote(asset){const safe=redact(asset);const runId=String(safe.run_id||safe.runId||`asset-${crypto.randomUUID()}`);return emit({stream:"RESULT",eventType:"KNOWLEDGE_ASSET",runId,payload:{record_type:"knowledge_asset",asset:safe},severity:"info"});}
 async function flushOutbox({limit=100}={}){const files=fs.readdirSync(outboxDir).filter(x=>x.endsWith(".json")).sort().slice(0,Math.max(1,Number(limit)||100));let delivered=0;const failures=[];for(const name of files){const file=path.join(outboxDir,name);try{const parsed=JSON.parse(fs.readFileSync(file,"utf8"));delete parsed.delivery;await post(parsed);fs.unlinkSync(file);delivered++;}catch(error){failures.push({file:name,error:String(error?.message||error)});break;}}return {delivered,pending:fs.readdirSync(outboxDir).filter(x=>x.endsWith(".json")).length,failures};}
 return {endpoint,projectId,outboxDir,emit,promote,flushOutbox,redact};}
module.exports={STREAMS,createTgserverAssetAdapter,redact};
