"use strict";
const fs=require("node:fs"),path=require("node:path"),cp=require("node:child_process"),{pathToFileURL,fileURLToPath}=require("node:url");
function findPosition(file,symbol){const s=fs.readFileSync(file,"utf8"),re=new RegExp(`\\b${String(symbol).replace(/[.*+?^${}()|[\\]\\]/g,"\\$&")}\\b`),m=re.exec(s);if(!m)return null;const pre=s.slice(0,m.index),lines=pre.split(/\r?\n/);return {line:lines.length-1,character:lines.at(-1).length};}
function normalizeLocations(v){const a=Array.isArray(v)?v:(v?[v]:[]);return a.map(x=>{const uri=x?.uri||x?.targetUri;let p=x?.path;if(!p&&typeof uri==="string"&&uri.startsWith("file:"))p=fileURLToPath(uri);return p?{...x,path:p}:null}).filter(Boolean);}
class TypeScript7LspClient{
  constructor({rootDir,command=process.env.DEBUG_AI_TS_LSP_COMMAND||"tsc",args=["--lsp","--stdio"],spawn=cp.spawn,timeoutMs=15000}={}){this.rootDir=path.resolve(rootDir||process.cwd());this.command=command;this.args=args;this.spawnImpl=spawn;this.timeoutMs=timeoutMs;this.seq=0;this.pending=new Map();this.buf=Buffer.alloc(0);this.proc=null;}
  async start(){if(this.proc)return true;this.proc=this.spawnImpl(this.command,this.args,{cwd:this.rootDir,stdio:["pipe","pipe","pipe"]});this.proc.stdout.on("data",c=>this._data(c));this.proc.on("exit",code=>{for(const p of this.pending.values())p.reject(new Error(`TS7_LSP_EXIT_${code}`));this.pending.clear();this.proc=null;});await this.request("initialize",{processId:process.pid,rootUri:pathToFileURL(this.rootDir).href,capabilities:{textDocument:{definition:{},references:{},documentSymbol:{}}},workspaceFolders:[{uri:pathToFileURL(this.rootDir).href,name:path.basename(this.rootDir)}]});this.notify("initialized",{});return true;}
  _write(msg){const raw=Buffer.from(JSON.stringify(msg));this.proc.stdin.write(Buffer.concat([Buffer.from(`Content-Length: ${raw.length}\r\n\r\n`),raw]));}
  _data(c){this.buf=Buffer.concat([this.buf,Buffer.from(c)]);for(;;){const h=this.buf.indexOf("\r\n\r\n");if(h<0)return;const head=this.buf.slice(0,h).toString(),m=/Content-Length:\s*(\d+)/i.exec(head);if(!m){this.buf=this.buf.slice(h+4);continue}const n=Number(m[1]);if(this.buf.length<h+4+n)return;const raw=this.buf.slice(h+4,h+4+n).toString();this.buf=this.buf.slice(h+4+n);let msg;try{msg=JSON.parse(raw)}catch{continue}if(Object.prototype.hasOwnProperty.call(msg,"id")&&this.pending.has(msg.id)){const p=this.pending.get(msg.id);this.pending.delete(msg.id);msg.error?p.reject(new Error(msg.error.message||"TS7_LSP_ERROR")):p.resolve(msg.result);}}}
  request(method,params={}){if(!this.proc)throw new Error("TS7_LSP_NOT_STARTED");const id=++this.seq;return new Promise((resolve,reject)=>{const t=setTimeout(()=>{this.pending.delete(id);reject(new Error(`TS7_LSP_TIMEOUT:${method}`));},this.timeoutMs);this.pending.set(id,{resolve:v=>{clearTimeout(t);resolve(v)},reject:e=>{clearTimeout(t);reject(e)}});this._write({jsonrpc:"2.0",id,method,params});});}
  notify(method,params={}){if(!this.proc)throw new Error("TS7_LSP_NOT_STARTED");this._write({jsonrpc:"2.0",method,params});}
  open(file,languageId="typescript"){const f=path.resolve(file);this.notify("textDocument/didOpen",{textDocument:{uri:pathToFileURL(f).href,languageId,version:1,text:fs.readFileSync(f,"utf8")}});}
  documentSymbols(file){return this.request("textDocument/documentSymbol",{textDocument:{uri:pathToFileURL(path.resolve(file)).href}});}
  async definition(file,symbol){const p=findPosition(file,symbol);if(!p)return [];return normalizeLocations(await this.request("textDocument/definition",{textDocument:{uri:pathToFileURL(path.resolve(file)).href},position:p}));}
  async references(file,symbol){const p=findPosition(file,symbol);if(!p)return [];return normalizeLocations(await this.request("textDocument/references",{textDocument:{uri:pathToFileURL(path.resolve(file)).href},position:p,context:{includeDeclaration:true}}));}
  async stop(){if(!this.proc)return;try{await this.request("shutdown",{})}catch{}try{this.notify("exit",{})}catch{}try{this.proc.kill()}catch{}this.proc=null;}
}
module.exports={TypeScript7LspClient,normalizeLocations,findPosition};
