#!/usr/bin/env bash
set -u
set -o pipefail
REPO="${DEBUG_AI_HOST_REPO:-/home/admin1/projects/debug-ai}"
CONTAINER_REPO="/workspace/debug-ai"
QUEUE="$REPO/.debugai-input/server-command"
JQ_BIN="${DEBUG_AI_SERVER_COMMAND_JQ_BIN:-jq}"
GIT_BIN="${DEBUG_AI_SERVER_COMMAND_GIT_BIN:-git}"
TIMEOUT_BIN="${DEBUG_AI_SERVER_COMMAND_TIMEOUT_BIN:-timeout}"
DOCKER_BIN="${DEBUG_AI_SERVER_COMMAND_DOCKER_BIN:-docker}"
err_code=""; request_id=""; command_id=""; result_json="{}"
fail(){ err_code="${1:-ERROR}"; return 1; }
ensure_dir(){ mkdir -p -- "$1" && chmod 700 -- "$1"; }
atomic_json(){ local target="$1" json="$2" tmp; ensure_dir "$(dirname -- "$target")" || return 1; tmp="${target}.tmp-$$-$(date +%s%N)"; (umask 077; printf '%s\n' "$json" >"$tmp") || return 1; mv -f -- "$tmp" "$target"; }
run_timed(){ local seconds="$1"; shift; "$TIMEOUT_BIN" --signal=TERM --kill-after=2s "$seconds" "$@"; }
validate_request(){ local file="$1" now_ms expires; "$JQ_BIN" -e '.schema=="debugai.server-command-request/v1" and (.id|type=="string" and test("^cmd_[0-9a-f]{24}$")) and .action=="read" and ((.command_id=="project.pwd" or .command_id=="project.git_head" or .command_id=="project.git_status" or .command_id=="service.debug_ai_state" or .command_id=="service.sandbox_state")) and .repo=="/workspace/debug-ai" and (.expires_at|type=="number")' "$file" >/dev/null || fail REQUEST_SCHEMA_OR_BOUNDARY_INVALID || return 1; request_id="$("$JQ_BIN" -r '.id' "$file")"; command_id="$("$JQ_BIN" -r '.command_id' "$file")"; expires="$("$JQ_BIN" -r '.expires_at|floor' "$file")"; now_ms="$(date +%s%3N)"; [ "$now_ms" -le "$expires" ] || fail REQUEST_EXPIRED || return 1; }
run_read_command(){ local output; case "$command_id" in project.pwd) output="$(cd "$REPO" && pwd -P)" || { fail COMMAND_EXEC_FAILED; return 1; };; project.git_head) output="$(cd "$REPO" && run_timed 5s "$GIT_BIN" rev-parse HEAD)" || { fail COMMAND_EXEC_FAILED; return 1; };;
project.git_status) branch="$(cd "$REPO" && run_timed 5s "$GIT_BIN" branch --show-current)" || { fail COMMAND_EXEC_FAILED; return 1; }; dirty="$(cd "$REPO" && { "$GIT_BIN" diff --name-only; "$GIT_BIN" diff --cached --name-only; "$GIT_BIN" ls-files --others --exclude-standard; } | sed '/^$/d;/^\.debugai-input\//d' | LC_ALL=C sort -u | wc -l | tr -d '[:space:]')" || { fail COMMAND_EXEC_FAILED; return 1; }; output="branch=$branch|dirty_count=$dirty";;
service.debug_ai_state) cid="$(cd "$REPO" && "$DOCKER_BIN" compose ps -q debug-ai 2>/dev/null | head -n1)"; [ -n "$cid" ] || { fail COMMAND_EXEC_FAILED; return 1; }; output="$("$DOCKER_BIN" inspect -f '{{.State.Status}}|{{if .State.Health}}{{.State.Health.Status}}{{else}}NONE{{end}}' "$cid" 2>/dev/null)" || { fail COMMAND_EXEC_FAILED; return 1; };;
service.sandbox_state) cid="$(cd "$REPO" && "$DOCKER_BIN" compose ps -q sandbox-runner 2>/dev/null | head -n1)"; [ -n "$cid" ] || { fail COMMAND_EXEC_FAILED; return 1; }; output="$("$DOCKER_BIN" inspect -f '{{.State.Status}}|{{if .State.Health}}{{.State.Health.Status}}{{else}}NONE{{end}}' "$cid" 2>/dev/null)" || { fail COMMAND_EXEC_FAILED; return 1; };;
*) fail COMMAND_NOT_ALLOWED; return 1;; esac; [ "${#output}" -le 4096 ] || { fail COMMAND_OUTPUT_TOO_LARGE; return 1; }; result_json="$("$JQ_BIN" -n --arg command_id "$command_id" --arg stdout "$output" '{command_id:$command_id,stdout:$stdout,exit_code:0,read_only:true}')"; }
process_file(){ local source="$1" processing done_dir failed_dir started finished status id_for_status; started="$(date +%s%3N)"; processing="$QUEUE/processing/$(basename -- "$source")"; done_dir="$QUEUE/done"; failed_dir="$QUEUE/failed"; ensure_dir "$QUEUE/processing" || return 1; ensure_dir "$done_dir" || return 1; ensure_dir "$failed_dir" || return 1; mv -- "$source" "$processing" || return 1; request_id=""; command_id=""; err_code=""; result_json="{}"; validate_request "$processing" && run_read_command || true; finished="$(date +%s%3N)"; id_for_status="$request_id"; [[ "$id_for_status" =~ ^cmd_[0-9a-f]{24}$ ]] || id_for_status="invalid_${finished}"; if [ -z "$err_code" ]; then status="$("$JQ_BIN" -n --arg id "$request_id" --arg command_id "$command_id" --argjson started "$started" --argjson finished "$finished" --argjson result "$result_json" '{schema:"debugai.server-command-status/v1",id:$id,command_id:$command_id,started_at:$started,state:"PASS",finished_at:$finished,result:$result}')"; atomic_json "$QUEUE/status/${id_for_status}.json" "$status" || return 1; mv -- "$processing" "$done_dir/$(basename -- "$processing")"; else status="$("$JQ_BIN" -n --arg id "$id_for_status" --arg command_id "$command_id" --argjson started "$started" --argjson finished "$finished" --arg error "${err_code:0:120}" '{schema:"debugai.server-command-status/v1",id:$id,command_id:$command_id,started_at:$started,state:"FAIL",finished_at:$finished,error:$error}')"; atomic_json "$QUEUE/status/${id_for_status}.json" "$status" || return 1; mv -- "$processing" "$failed_dir/$(basename -- "$processing")"; fi; }
main(){ local lock_dir request_dir name count=0 cmd; for cmd in "$JQ_BIN" "$GIT_BIN" "$TIMEOUT_BIN" "$DOCKER_BIN"; do command -v "$cmd" >/dev/null 2>&1 || { printf 'debugai-server-command-runner:DEPENDENCY_MISSING:%s\n' "$cmd" >&2; return 1; }; done; [ -d "$REPO/.git" ] || { printf 'debugai-server-command-runner:REPO_INVALID\n' >&2; return 1; }; request_dir="$QUEUE/requests"; ensure_dir "$request_dir" || return 1; ensure_dir "$QUEUE/status" || return 1; lock_dir="$QUEUE/.runner.lock"; if ! mkdir -- "$lock_dir" 2>/dev/null; then return 0; fi; trap 'rmdir -- "$lock_dir" 2>/dev/null || true' EXIT INT TERM; while IFS= read -r name; do [ -n "$name" ] || continue; process_file "$request_dir/$name" || return 1; count=$((count+1)); [ "$count" -ge 8 ] && break; done < <(find "$request_dir" -maxdepth 1 -type f -name 'cmd_*.json' -printf '%f\n' | LC_ALL=C sort); trap - EXIT INT TERM; rmdir -- "$lock_dir" 2>/dev/null || true; }
main "$@"
