#!/usr/bin/env bash
set -u
set -o pipefail
REPO="${DEBUG_AI_HOST_REPO:-/home/admin1/projects/debug-ai}"
CONTAINER_REPO="/workspace/debug-ai"
QUEUE="$REPO/.debugai-input/server-command"
JQ_BIN="${DEBUG_AI_SERVER_COMMAND_JQ_BIN:-jq}"
GIT_BIN="${DEBUG_AI_SERVER_COMMAND_GIT_BIN:-git}"
TIMEOUT_BIN="${DEBUG_AI_SERVER_COMMAND_TIMEOUT_BIN:-timeout}"
DOCKER_BIN="${DEBUG_AI_SERVER_COMMAND_DOCKER_BIN:-docker}"
CURL_BIN="${DEBUG_AI_SERVER_COMMAND_CURL_BIN:-curl}"
DF_BIN="${DEBUG_AI_SERVER_COMMAND_DF_BIN:-df}"
GH_BIN="${DEBUG_AI_SERVER_COMMAND_GH_BIN:-gh}"
err_code=""; request_id=""; command_id=""; result_json="{}"
fail(){ err_code="${1:-ERROR}"; return 1; }
ensure_dir(){ mkdir -p -- "$1" && chmod 700 -- "$1"; }
atomic_json(){ local target="$1" json="$2" tmp; ensure_dir "$(dirname -- "$target")" || return 1; tmp="${target}.tmp-$$-$(date +%s%N)"; (umask 077; printf '%s\n' "$json" >"$tmp") || return 1; mv -f -- "$tmp" "$target"; }
run_timed(){ local seconds="$1"; shift; "$TIMEOUT_BIN" --signal=TERM --kill-after=2s "$seconds" "$@"; }
validate_request(){ local file="$1" now_ms expires; "$JQ_BIN" -e '.schema=="debugai.server-command-request/v1" and (.id|type=="string" and test("^cmd_[0-9a-f]{24}$")) and .action=="read" and ((.command_id=="project.pwd" or .command_id=="project.git_head" or .command_id=="project.git_status" or .command_id=="project.git_changed_paths" or .command_id=="project.git_recent_commits" or .command_id=="service.debug_ai_state" or .command_id=="service.sandbox_state" or .command_id=="service.debug_ai_health" or .command_id=="system.disk_usage" or .command_id=="github.auth_status" or .command_id=="github.repo_view" or .command_id=="github.pr_current" or .command_id=="github.actions_recent" or .command_id=="github.control_current" or .command_id=="github.gh_read")) and .repo=="/workspace/debug-ai" and (if .command_id=="github.gh_read" then (.arguments|type=="array" and length>=1 and length<=16) else true end) and (.expires_at|type=="number")' "$file" >/dev/null || fail REQUEST_SCHEMA_OR_BOUNDARY_INVALID || return 1; request_id="$("$JQ_BIN" -r '.id' "$file")"; command_id="$("$JQ_BIN" -r '.command_id' "$file")"; expires="$("$JQ_BIN" -r '.expires_at|floor' "$file")"; now_ms="$(date +%s%3N)"; [ "$now_ms" -le "$expires" ] || fail REQUEST_EXPIRED || return 1; }
run_read_command(){ local output; case "$command_id" in project.pwd) output="$(cd "$REPO" && pwd -P)" || { fail COMMAND_EXEC_FAILED; return 1; };; project.git_head) output="$(cd "$REPO" && run_timed 5s "$GIT_BIN" rev-parse HEAD)" || { fail COMMAND_EXEC_FAILED; return 1; };;
project.git_status) branch="$(cd "$REPO" && run_timed 5s "$GIT_BIN" branch --show-current)" || { fail COMMAND_EXEC_FAILED; return 1; }; dirty="$(cd "$REPO" && { "$GIT_BIN" diff --name-only; "$GIT_BIN" diff --cached --name-only; "$GIT_BIN" ls-files --others --exclude-standard; } | sed '/^$/d;/^\.debugai-input\//d' | LC_ALL=C sort -u | wc -l | tr -d '[:space:]')" || { fail COMMAND_EXEC_FAILED; return 1; }; output="branch=$branch|dirty_count=$dirty";;
project.git_changed_paths) output="$(cd "$REPO" && { "$GIT_BIN" diff --name-only; "$GIT_BIN" diff --cached --name-only; "$GIT_BIN" ls-files --others --exclude-standard; } | sed '/^$/d;/^\.debugai-input\//d' | LC_ALL=C sort -u | head -n 40)" || { fail COMMAND_EXEC_FAILED; return 1; };;
project.git_recent_commits) output="$(cd "$REPO" && run_timed 5s "$GIT_BIN" log -n 8 --format='%h %s')" || { fail COMMAND_EXEC_FAILED; return 1; };;
service.debug_ai_state) cid="$(cd "$REPO" && "$DOCKER_BIN" compose ps -q debug-ai 2>/dev/null | head -n1)"; [ -n "$cid" ] || { fail COMMAND_EXEC_FAILED; return 1; }; output="$("$DOCKER_BIN" inspect -f '{{.State.Status}}|{{if .State.Health}}{{.State.Health.Status}}{{else}}NONE{{end}}' "$cid" 2>/dev/null)" || { fail COMMAND_EXEC_FAILED; return 1; };;
service.sandbox_state) cid="$(cd "$REPO" && "$DOCKER_BIN" compose ps -q sandbox-runner 2>/dev/null | head -n1)"; [ -n "$cid" ] || { fail COMMAND_EXEC_FAILED; return 1; }; output="$("$DOCKER_BIN" inspect -f '{{.State.Status}}|{{if .State.Health}}{{.State.Health.Status}}{{else}}NONE{{end}}' "$cid" 2>/dev/null)" || { fail COMMAND_EXEC_FAILED; return 1; };;
service.debug_ai_health) code="$("$CURL_BIN" -sS -o /dev/null -w '%{http_code}' --connect-timeout 2 --max-time 5 http://127.0.0.1:8787/health)" || { fail COMMAND_EXEC_FAILED; return 1; }; output="http_status=$code";;
system.disk_usage) output="$("$DF_BIN" -Pk "$REPO" | awk 'NR==2 {print "blocks_kb="$2"|used_kb="$3"|available_kb="$4"|used_percent="$5}')" || { fail COMMAND_EXEC_FAILED; return 1; };;
github.auth_status) command -v "$GH_BIN" >/dev/null 2>&1 || { fail GH_CLI_UNAVAILABLE; return 1; }; output="$("$GH_BIN" auth status -h github.com 2>&1 | sed -E 's/(Token: ).*/\1[REDACTED]/; s/(oauth_token: ).*/\1[REDACTED]/' | head -n 12)" || { fail GH_AUTH_UNAVAILABLE; return 1; };;
github.repo_view) command -v "$GH_BIN" >/dev/null 2>&1 || { fail GH_CLI_UNAVAILABLE; return 1; }; output="$("$GH_BIN" repo view seigo-gace/debug-ai --json nameWithOwner,defaultBranchRef,isPrivate,url 2>/dev/null)" || { fail COMMAND_EXEC_FAILED; return 1; };;
github.pr_current) command -v "$GH_BIN" >/dev/null 2>&1 || { fail GH_CLI_UNAVAILABLE; return 1; }; branch="$(cd "$REPO" && "$GIT_BIN" branch --show-current)" || { fail COMMAND_EXEC_FAILED; return 1; }; output="$("$GH_BIN" pr view "$branch" --repo seigo-gace/debug-ai --json number,state,isDraft,mergeable,headRefName,headRefOid,baseRefName,url 2>/dev/null)" || { fail COMMAND_EXEC_FAILED; return 1; };;
github.actions_recent) command -v "$GH_BIN" >/dev/null 2>&1 || { fail GH_CLI_UNAVAILABLE; return 1; }; branch="$(cd "$REPO" && "$GIT_BIN" branch --show-current)" || { fail COMMAND_EXEC_FAILED; return 1; }; output="$("$GH_BIN" run list --repo seigo-gace/debug-ai --branch "$branch" --limit 8 --json databaseId,name,status,conclusion,headSha,event,url 2>/dev/null)" || { fail COMMAND_EXEC_FAILED; return 1; };;
github.control_current) command -v "$GH_BIN" >/dev/null 2>&1 || { fail GH_CLI_UNAVAILABLE; return 1; }; output="$("$GH_BIN" issue view 41 --repo seigo-gace/debug-ai --json number,title,state,updatedAt,url,body 2>/dev/null | "$JQ_BIN" -c '{number,title,state,updatedAt,url,body:(.body|tostring|.[0:2500])}')" || { fail COMMAND_EXEC_FAILED; return 1; };;
github.gh_read) command -v "$GH_BIN" >/dev/null 2>&1 || { fail GH_CLI_UNAVAILABLE; return 1; }; mapfile -t gh_args < <("$JQ_BIN" -r '.arguments[]' "$processing"); [ "${#gh_args[@]}" -ge 1 ] || { fail REQUEST_SCHEMA_OR_BOUNDARY_INVALID; return 1; }; output="$(cd "$REPO" && run_timed 10s "$GH_BIN" "${gh_args[@]}" 2>&1)" || { fail COMMAND_EXEC_FAILED; return 1; };;
*) fail COMMAND_NOT_ALLOWED; return 1;; esac; [ "${#output}" -le 4096 ] || { fail COMMAND_OUTPUT_TOO_LARGE; return 1; }; result_json="$("$JQ_BIN" -n --arg command_id "$command_id" --arg stdout "$output" '{command_id:$command_id,stdout:$stdout,exit_code:0,read_only:true}')"; }
process_file(){ local source="$1" processing done_dir failed_dir started finished status id_for_status; started="$(date +%s%3N)"; processing="$QUEUE/processing/$(basename -- "$source")"; done_dir="$QUEUE/done"; failed_dir="$QUEUE/failed"; ensure_dir "$QUEUE/processing" || return 1; ensure_dir "$done_dir" || return 1; ensure_dir "$failed_dir" || return 1; mv -- "$source" "$processing" || return 1; request_id=""; command_id=""; err_code=""; result_json="{}"; validate_request "$processing" && run_read_command || true; finished="$(date +%s%3N)"; id_for_status="$request_id"; [[ "$id_for_status" =~ ^cmd_[0-9a-f]{24}$ ]] || id_for_status="invalid_${finished}"; if [ -z "$err_code" ]; then status="$("$JQ_BIN" -n --arg id "$request_id" --arg command_id "$command_id" --argjson started "$started" --argjson finished "$finished" --argjson result "$result_json" '{schema:"debugai.server-command-status/v1",id:$id,command_id:$command_id,started_at:$started,state:"PASS",finished_at:$finished,result:$result}')"; atomic_json "$QUEUE/status/${id_for_status}.json" "$status" || return 1; mv -- "$processing" "$done_dir/$(basename -- "$processing")"; else status="$("$JQ_BIN" -n --arg id "$id_for_status" --arg command_id "$command_id" --argjson started "$started" --argjson finished "$finished" --arg error "${err_code:0:120}" '{schema:"debugai.server-command-status/v1",id:$id,command_id:$command_id,started_at:$started,state:"FAIL",finished_at:$finished,error:$error}')"; atomic_json "$QUEUE/status/${id_for_status}.json" "$status" || return 1; mv -- "$processing" "$failed_dir/$(basename -- "$processing")"; fi; }
main(){ local lock_dir request_dir name count=0 cmd; for cmd in "$JQ_BIN" "$GIT_BIN" "$TIMEOUT_BIN" "$DOCKER_BIN" "$CURL_BIN" "$DF_BIN"; do command -v "$cmd" >/dev/null 2>&1 || { printf 'debugai-server-command-runner:DEPENDENCY_MISSING:%s\n' "$cmd" >&2; return 1; }; done; [ -d "$REPO/.git" ] || { printf 'debugai-server-command-runner:REPO_INVALID\n' >&2; return 1; }; request_dir="$QUEUE/requests"; ensure_dir "$request_dir" || return 1; ensure_dir "$QUEUE/status" || return 1; lock_dir="$QUEUE/.runner.lock"; if ! mkdir -- "$lock_dir" 2>/dev/null; then return 0; fi; trap 'rmdir -- "$lock_dir" 2>/dev/null || true' EXIT INT TERM; while IFS= read -r name; do [ -n "$name" ] || continue; process_file "$request_dir/$name" || return 1; count=$((count+1)); [ "$count" -ge 8 ] && break; done < <(find "$request_dir" -maxdepth 1 -type f -name 'cmd_*.json' -printf '%f\n' | LC_ALL=C sort); trap - EXIT INT TERM; rmdir -- "$lock_dir" 2>/dev/null || true; }
main "$@"
