"use strict";
const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const os=require('node:os');const path=require('node:path');const zlib=require('node:zlib');
const {parseArtifactZip,crc32,hash}=require('../control/actions-artifact-zip.js');
const {ingestActionsArtifact,loadArtifactEvidence,sanitizeArtifactText}=require('../control/actions-artifact-evidence.js');
const {RuntimeEvidenceStore}=require('../runtime-evidence.js');const {makeEvidenceRecord}=require('../control/evidence-registry.js');
function zip(items){const locals=[],centrals=[];let offset=0;for(const item of items){const name=Buffer.from(item.name),raw=Buffer.from(item.text||''),data=item.method===8?zlib.deflateRawSync(raw):raw,local=Buffer.alloc(30),central=Buffer.alloc(46);local.writeUInt32LE(0x04034b50);local.writeUInt16LE(20,4);local.writeUInt16LE(item.flags||0,6);local.writeUInt16LE(item.method||0,8);local.writeUInt32LE(crc32(raw),14);local.writeUInt32LE(data.length,18);local.writeUInt32LE(raw.length,22);local.writeUInt16LE(name.length,26);central.writeUInt32LE(0x02014b50);central.writeUInt16LE(0x0314,4);central.writeUInt16LE(20,6);local.copy(central,8,6,10);central.writeUInt32LE(crc32(raw),16);central.writeUInt32LE(data.length,20);central.writeUInt32LE(raw.length,24);central.writeUInt16LE(name.length,28);central.writeUInt32LE(((item.mode||0o100600)<<16)>>>0,38);central.writeUInt32LE(offset,42);locals.push(local,name,data);centrals.push(central,name);offset+=30+name.length+data.length;}const c=Buffer.concat(centrals),e=Buffer.alloc(22);e.writeUInt32LE(0x06054b50);e.writeUInt16LE(items.length,8);e.writeUInt16LE(items.length,10);e.writeUInt32LE(c.length,12);e.writeUInt32LE(offset,16);return Buffer.concat([...locals,c,e]);}
test('restricted stored/deflate log intake keeps hashes without extraction',()=>{for(const method of [0,8]){const result=parseArtifactZip(zip([{name:'tests/verify.log',text:'failed assertion',method}]));assert.equal(result.entries[0].text,'failed assertion');assert.equal(result.entries[0].content_sha256,hash(Buffer.from('failed assertion')));}});
for(const name of ['../x.log','/x.log','C:/x.log','a\\x.log','a/./x.log','a//x.log','a\nx.log','.env.txt','token.secret.txt','x.zip','x.js','a./x.log'])test('reject unsafe '+JSON.stringify(name),()=>assert.throws(()=>parseArtifactZip(zip([{name,text:'a'}]))));
for(const [label,items] of [['duplicate',[{name:'x.log'},{name:'x.log'}]],['case collision',[{name:'X.log'},{name:'x.log'}]],['symlink',[{name:'x.log',mode:0o120777}]],['device',[{name:'x.log',mode:0o020600}]],['encrypted',[{name:'x.log',flags:1}]],['unsupported',[{name:'x.log',method:99}]],['ratio bomb',[{name:'x.log',method:8,text:'A'.repeat(100000)}]],['too many',Array.from({length:129},(_,i)=>({name:i+'.log'}))]])test('reject '+label,()=>assert.throws(()=>parseArtifactZip(zip(items))));
test('reject CRC, truncation, forged size and name mismatches',()=>{const valid=zip([{name:'x.log',text:'check'}]);for(const mutate of [b=>b.subarray(0,b.length-1),b=>{b[35]^=1;return b;},b=>{b.writeUInt32LE(1,18);return b;},b=>{b[30]=89;return b;}])assert.throws(()=>parseArtifactZip(mutate(Buffer.from(valid))));});
test('masks assignment, authorization, cookies, known tokens and multiline private keys',()=>{const text='CUSTOM_CREDENTIAL=hello\nAuthorization: Basic abc\nCookie: sid=secret\n{"password":"has spaces"}\nghp_'+ 'a'.repeat(30)+'\n-----BEGIN RSA '+'PRIVATE KEY-----\nhidden\n-----END RSA '+'PRIVATE KEY-----';const safe=sanitizeArtifactText(text);for(const value of ['hello','Basic abc','sid=secret','has spaces','hidden','a'.repeat(30)])assert.ok(!safe.includes(value));});
function fixture(){const headSha='a'.repeat(40),archive=zip([{name:'verify.log',text:'not ok 1\nAuthorization: Bearer secret\nENV_PASSWORD=hidden'}]),repo={id:1,node_id:'R1',full_name:'owner/repo',owner:{login:'owner'},permissions:{admin:true}},registry={schema:'gace.workspace-master-internal-registry/v1',master_principal:'owner',project:{node_id:'P1'},repositories:[{schema:'debugai.master-internal-delegation/v1',repository:'owner/repo',repository_id:1,repository_node_id:'R1',repository_owner:'owner',master_principal:'owner',enabled:true,revoked:false,project:{owner:'owner',number:1,node_id:'P1',item_id:'I1',control_url:'issue'}}]},responses={user:{login:'owner'},'repos/owner/repo':repo,'repos/owner/repo/actions/runs/2':{id:2,repository:repo,head_repository:repo,head_sha:headSha,run_attempt:1,status:'completed',conclusion:'failure',workflow_id:4,event:'push'},'repos/owner/repo/actions/runs/2/attempts/1/jobs?per_page=100&page=1':{total_count:1,jobs:[{id:5,run_id:2,head_sha:headSha,run_attempt:1,conclusion:'failure'}]},'repos/owner/repo/actions/artifacts/3':{id:3,expired:false,workflow_run:{id:2,head_sha:headSha,repository_id:1,head_repository_id:1},size_in_bytes:archive.length,digest:'sha256:'+hash(archive),created_at:'2026-10-09T00:00:00Z',expires_at:'2099-01-01T00:00:00Z'}};let downloads=0;return{responses,registry,request:{repository:'owner/repo',runId:2,artifactId:3,headSha,attempt:1,evidenceRunId:'artifact_test'},reader:{json:async p=>responses[p],project:async()=>({items:[{id:'I1',content:{repository:'owner/repo',url:'issue'}}]}),download:async()=>{downloads++;return archive;}},downloads:()=>downloads};}
test('real existing store registration, content IDs, diagnosis handoff, ZERO correlation and retention',async()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'artifact-test-'));try{const store=new RuntimeEvidenceStore(dir,{retentionMs:100}),f=fixture(),events=[],result=await ingestActionsArtifact({...f.request,registry:f.registry,reader:f.reader,runtimeEvidence:store,tgserver:{log:async e=>events.push(e)}});assert.equal(f.downloads(),1);assert.equal(result.records.length,1);assert.equal(events[0].github_run_id,2);assert.equal(events[0].head_sha,f.request.headSha);assert.equal(result.diagnosis_input[0].parent_evidence_id,result.evidence_ids[0]);const local=loadArtifactEvidence(store,'artifact_test',result.evidence_ids);assert.equal(makeEvidenceRecord('LOCAL_RUNTIME',local[0]).evidence_id,result.evidence_ids[0]);assert.ok(!JSON.stringify(result).includes('hidden'));assert.equal(local[0].observed_outcome,'UNKNOWN');store.rotate(Date.now()+1000);assert.throws(()=>loadArtifactEvidence(store,'artifact_test',result.evidence_ids),/NOT_AVAILABLE/);}finally{fs.rmSync(dir,{recursive:true,force:true});}});
for(const [name,change] of [['repo identity',f=>f.responses['repos/owner/repo'].id=99],['wrong SHA',f=>f.request.headSha='b'.repeat(40)],['attempt',f=>f.request.attempt=2],['expired',f=>f.responses['repos/owner/repo/actions/artifacts/3'].expired=true],['digest',f=>f.responses['repos/owner/repo/actions/artifacts/3'].digest='sha256:'+'b'.repeat(64)],['job mismatch',f=>f.responses['repos/owner/repo/actions/runs/2/attempts/1/jobs?per_page=100&page=1'].jobs[0].head_sha='b'.repeat(40)],['revoked',f=>f.registry.repositories[0].revoked=true]])test('reject '+name+' without Evidence or ZERO publication',async()=>{const f=fixture();change(f);let published=0;await assert.rejects(ingestActionsArtifact({...f.request,registry:f.registry,reader:f.reader,runtimeEvidence:{maxRecordBytes:2**21,write:()=>published++},tgserver:{log:async()=>published++}}));assert.equal(published,0);});
module.exports={zip};
test('registered artifact enters existing Diagnoser tool loop with no provider calls',async()=>{const f=fixture(),records=[];const result=await ingestActionsArtifact({...f.request,registry:f.registry,reader:f.reader,runtimeEvidence:{maxRecordBytes:2**21,write:(_,__,r)=>records.push(r)},tgserver:{log:async()=>{}}});const {runRoleWithReadOnlyTools}=require('../control/tool-loop.js');let consumed=false;const out=await runRoleWithReadOnlyTools({role:'diagnoser',user:JSON.stringify({localEvidence:result.records}),baseEvidenceIds:result.evidence_ids,strictEvidenceRefs:true,aiCore:{call:async(role,input)=>{assert.equal(role,'diagnoser');assert.ok(input.user.includes(result.evidence_ids[0]));assert.ok(!input.user.includes('hidden'));consumed=true;return{content:JSON.stringify({diagnosis_status:'HYPOTHESES_RETAINED',hypotheses:[{id:'H_LOG',status:'HYPOTHESIS',evidence_refs:result.evidence_ids,counter_evidence_refs:[],falsification_condition:'Reproduce the observed assertion under the exact source'}],confirmed_root_cause:null,unsupported_claims:['Artifact absence is not proof of failure']})};}}});assert.ok(consumed);assert.equal(out.tool_loop.parse_status,'FINAL');assert.equal(out.validated_output.confirmed_root_cause,null);});
test('reject archive member cap and hierarchy collisions',()=>{assert.throws(()=>parseArtifactZip(zip([{name:'x.log',text:'A'.repeat(2*1024**2+1)}])));assert.throws(()=>parseArtifactZip(zip([{name:'x.log',text:'a'},{name:'x.log/y.txt',text:'b'}])));});
test('reject nested archive bytes even under allowed extension',()=>{assert.throws(()=>parseArtifactZip(zip([{name:'x.log',text:zip([{name:'y.log',text:'z'}])}])));});
test('reject concurrent rerun after immutable download without publishing',async()=>{const f=fixture();const download=f.reader.download;f.reader.download=async(...args)=>{const bytes=await download(...args);f.responses['repos/owner/repo/actions/runs/2'].run_attempt=2;return bytes;};let writes=0;await assert.rejects(ingestActionsArtifact({...f.request,registry:f.registry,reader:f.reader,runtimeEvidence:{maxRecordBytes:2**21,write:()=>writes++},tgserver:{log:async()=>writes++}}),/CHANGED_DURING_DOWNLOAD/);assert.equal(writes,0);});
test('gh transport fixes GitHub host, GET, deadline and buffer; errors conceal stderr',async()=>{const {createGhArtifactReader}=require('../control/actions-artifact-github.js');const calls=[];const reader=createGhArtifactReader({execImpl:(command,args,options,cb)=>{calls.push({command,args,options});cb(null,Buffer.from('{}'));}});await reader.json('user');await reader.download('owner/repo',3);assert.equal(calls[0].command,'gh');assert.deepEqual(calls[0].args,['api','--hostname','github.com','--method','GET','user']);assert.equal(calls[1].options.maxBuffer,4*1024**2);assert.equal(calls[1].options.timeout,30000);const denied=createGhArtifactReader({execImpl:(_,__,___,cb)=>cb(new Error('Bearer secret'))});await assert.rejects(denied.download('owner/repo',3),e=>!e.message.includes('secret'));});
