"use strict";
const test=require("node:test");const assert=require("node:assert/strict");
const C=require("../../orchestrator/durable-contracts.js");
const M=require("../../orchestrator/execution-manifest.js");
const {CommitProtocol}=require("../../orchestrator/commit-protocol.js");
class MemIO{constructor(){this.m=new Map()}readRecord(p,{allowMissing=false}={}){if(!this.m.has(p)){if(allowMissing)return null;throw new Error("MISSING:"+p)}return structuredClone(this.m.get(p))}writeImmutableRecord(p,r){if(this.m.has(p)){assert.deepEqual(this.m.get(p),r);return{written:false}}this.m.set(p,structuredClone(r));return{written:true}}replaceRecord(p,r){this.m.set(p,structuredClone(r));return{written:true}}}
test("run-state v2 validates last_commit_id",()=>{const s=C.makeRunStateV2({request_hash:"a".repeat(64),project_dir:"/workspace/a",project_id:"a"});s.last_commit_id="cmt_x";assert.equal(C.validateRunStateV2(s),true)});
test("manifest evolution increments only requested counter",()=>{const m=M.makeInitialManifest({run_id:"run_a",request_digest:"b".repeat(64)});const n=M.incrementCounter(m,"tool_dispatches",1);assert.equal(n.job.tool_dispatches,1);assert.equal(n.job.model_dispatches,0);assert.notEqual(n.digest,m.digest)});
test("commit protocol fences stale generation and stale epoch",async()=>{const io=new MemIO(),cp=new CommitProtocol({io});const s=C.makeRunStateV2({request_hash:"f".repeat(64),project_dir:"/workspace/a",project_id:"a"});const m=M.makeInitialManifest({run_id:s.run_id,request_digest:"f".repeat(64)});const first=await cp.commit({runId:s.run_id,expected:{generation:0,execution_epoch:0},manifest:m,createIfMissing:true,initialState:s});assert.equal(first.generation,0);const m2=M.evolveManifest(m,{job:{status:C.JobStatus.RUNNING}});const second=await cp.commit({runId:s.run_id,expected:{generation:0,execution_epoch:0},manifest:m2,runStatePatch:{job_status:C.JobStatus.RUNNING}});assert.equal(second.generation,1);await assert.rejects(()=>cp.commit({runId:s.run_id,expected:{generation:0,execution_epoch:0},manifest:M.evolveManifest(m2)}),e=>e.code==="GENERATION_CONFLICT");const m3=M.evolveManifest(m2);const bumped=await cp.bumpEpoch({runId:s.run_id,expectedGeneration:1,expectedEpoch:0,manifest:m3});assert.equal(bumped.execution_epoch,1);await assert.rejects(()=>cp.commit({runId:s.run_id,expected:{generation:bumped.generation,execution_epoch:0},manifest:M.evolveManifest(m3)}),e=>e.code==="EPOCH_FENCED")});
