"use strict";
const test=require("node:test");
const assert=require("node:assert/strict");
const fs=require("node:fs");
const os=require("node:os");
const path=require("node:path");
const {PatchService,CANDIDATE_RETENTION_MS,PASS_BACKUP_RETENTION_MS}=require("../patch-service.js");
const {sweepPatchRetention}=require("../control/patch-retention-gc.js");

function makeRoot(){return fs.mkdtempSync(path.join(os.tmpdir(),"debugai-patch-gc-"));}
function createExpiredCandidate(runtimeRoot){const repo=path.join(runtimeRoot,"repo");fs.mkdirSync(repo,{recursive:true});fs.writeFileSync(path.join(repo,"a.txt"),"old\n");const service=new PatchService({runtimeRoot});const candidate=service.create({repo,selectedPaths:["a.txt"],task:"replace old",result:{summary:"test",operations:[{type:"replace",path:"a.txt",old:"old",new:"new"}]}});candidate.created_at=100;candidate.retention_ms=CANDIDATE_RETENTION_MS;candidate.retain_until=100+CANDIDATE_RETENTION_MS;const file=path.join(runtimeRoot,"patch-candidates",`${candidate.id}.json`);fs.writeFileSync(file,JSON.stringify(candidate,null,2));return candidate;}
function createBackup(runtimeRoot,candidate,{verifiedAt=100,expired=false,withRetention=true}={}){const backups=path.join(runtimeRoot,"patch-backups");fs.mkdirSync(backups,{recursive:true});const id=`${candidate.id}-tx1`,dir=path.join(backups,id);fs.mkdirSync(dir);fs.writeFileSync(path.join(dir,"payload.bin"),"backup");fs.writeFileSync(path.join(dir,"receipt.json"),JSON.stringify({schema:"patch-application/v2",transaction_id:id,candidate_id:candidate.id,candidate_hash:candidate.candidate_hash,files:[],rollback_available:true,backup_dir:dir,applied_at:new Date(verifiedAt).toISOString()},null,2));if(withRetention){const retainUntil=verifiedAt+PASS_BACKUP_RETENTION_MS;fs.writeFileSync(path.join(dir,"retention.json"),JSON.stringify({schema:"debugai.patch-backup-retention/v1",verification_pass:true,verified_at:verifiedAt,retain_until:retainUntil,retention_ms:PASS_BACKUP_RETENTION_MS},null,2));return{dir,retainUntil,now:expired?retainUntil:retainUntil-1};}return{dir,now:Number.MAX_SAFE_INTEGER};}

test("expired candidate is retained while a live backup references it",()=>{const root=makeRoot();try{const candidate=createExpiredCandidate(root),backup=createBackup(root,candidate,{verifiedAt:candidate.retain_until,expired:false}),now=candidate.retain_until+1;const report=sweepPatchRetention({runtimeRoot:root,now,maxDeletes:8});assert.equal(report.errors.length,0);assert.equal(report.candidate_deleted.length,0);assert.ok(report.skipped.some(x=>x.kind==="candidate"&&x.id===candidate.id&&x.reason==="BACKUP_REFERENCE_ACTIVE"));assert.ok(fs.existsSync(path.join(root,"patch-candidates",`${candidate.id}.json`)));assert.ok(fs.existsSync(backup.dir));}finally{fs.rmSync(root,{recursive:true,force:true});}});

test("expired backup is atomically quarantined then removed and candidate can be collected",()=>{const root=makeRoot();try{const candidate=createExpiredCandidate(root),backup=createBackup(root,candidate,{expired:true}),now=Math.max(candidate.retain_until,backup.retainUntil);const report=sweepPatchRetention({runtimeRoot:root,now,maxDeletes:8});assert.equal(report.errors.length,0);assert.equal(report.backup_deleted.length,1);assert.deepEqual(report.candidate_deleted,[candidate.id]);assert.equal(fs.existsSync(backup.dir),false);assert.equal(fs.readdirSync(path.join(root,"patch-backups-gc-quarantine")).length,0);assert.equal(fs.existsSync(path.join(root,"patch-candidates",`${candidate.id}.json`)),false);}finally{fs.rmSync(root,{recursive:true,force:true});}});

test("backup without verified retention receipt is preserved fail-closed and blocks candidate GC",()=>{const root=makeRoot();try{const candidate=createExpiredCandidate(root),backup=createBackup(root,candidate,{withRetention:false});const report=sweepPatchRetention({runtimeRoot:root,now:candidate.retain_until+1,maxDeletes:8});assert.equal(report.backup_deleted.length,0);assert.equal(report.candidate_deleted.length,0);assert.ok(report.errors.some(x=>x.kind==="backup"));assert.ok(report.skipped.some(x=>x.kind==="candidate"&&x.reason==="BACKUP_REFERENCE_SCAN_UNSAFE"));assert.ok(fs.existsSync(backup.dir));}finally{fs.rmSync(root,{recursive:true,force:true});}});

test("quarantine leftovers are recovered on the next sweep",()=>{const root=makeRoot();try{const quarantine=path.join(root,"patch-backups-gc-quarantine","stale-tx");fs.mkdirSync(quarantine,{recursive:true});fs.writeFileSync(path.join(quarantine,"partial.bin"),"x");const report=sweepPatchRetention({runtimeRoot:root,now:1,maxDeletes:8});assert.deepEqual(report.quarantine_recovered,["stale-tx"]);assert.equal(fs.existsSync(quarantine),false);}finally{fs.rmSync(root,{recursive:true,force:true});}});
