"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),os=require("node:os"),path=require("node:path");
const {ROLE_ORDER}=require("../control/skill-effect-suite.js"),{run,load}=require("../control/resumable-skill-effect-suite.js");
function tmp(){return path.join(fs.mkdtempSync(path.join(os.tmpdir(),"debugai-rse-")),"cp.json")}
function all(calls,opt={}){return Object.fromEntries(ROLE_ORDER.map(r=>{let failed=false,mod={SCHEMA:`test.${r}/v1`,CASES:[{id:"c1",input:{x:r}}],parseJson:JSON.parse,scoreCase(_c,v){return{score:v.mode==="on"?1:0,max_score:1}}};return[r,{mod,build:()=>({off:"OFF",on:"ON",selected_skill_ids:["s"]}),call:async({mode})=>{calls.push(`${r}:${mode}`);if(opt[r]?.failOnce===mode&&!failed){failed=true;throw Error("AI_CORE_TIMEOUT")}return{content:JSON.stringify({mode})}}}]}))}
function silent(){}
test("completed measurements are reused with zero new model calls",async()=>{let p=tmp(),a=[];let x=await run({checkpointPath:p,fp:"v1",emit:silent,heartbeatMs:60000,adapters:all(a)});assert.equal(x.completed,true);assert.equal(a.length,12);let b=[];let y=await run({checkpointPath:p,fp:"v1",emit:silent,heartbeatMs:60000,adapters:all(b)});assert.equal(y.completed,true);assert.deepEqual(b,[])});
test("only failed ON/OFF unit is retried on resume",async()=>{let p=tmp(),a=[];let x=await run({checkpointPath:p,fp:"v2",emit:silent,heartbeatMs:60000,adapters:all(a,{code_scout:{failOnce:"on"}})});assert.equal(x.completed,false);let c=load(p,"v2");assert.equal(c.roles.code_scout.cases.c1.off.status,"DONE");assert.equal(c.roles.code_scout.cases.c1.on.status,"FAILED");let b=[];let y=await run({checkpointPath:p,fp:"v2",emit:silent,heartbeatMs:60000,adapters:all(b)});assert.equal(y.completed,true);assert.deepEqual(b,["code_scout:on"])});
test("checkpoint is source-bound and fails closed after source change",async()=>{let p=tmp();await run({checkpointPath:p,fp:"a",emit:silent,heartbeatMs:60000,adapters:all([])});await assert.rejects(run({checkpointPath:p,fp:"b",emit:silent,heartbeatMs:60000,adapters:all([])}),/SKILL_CHECKPOINT_SOURCE_MISMATCH/)});
