"use strict";
// These are LOCAL_FIXTURE_ONLY integrity controls, not isolated construction proof.
const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),os=require("node:os"),path=require("node:path");
const runtime=require("../control/sandbox-runtime.js");
function fixture(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),"snapshot-integrity-")),repo=path.join(root,"source"),dst=path.join(root,"copy");fs.mkdirSync(repo);fs.writeFileSync(path.join(repo,"a.js"),"module.exports=1;\n",{mode:0o755});fs.mkdirSync(path.join(repo,"assets"));fs.writeFileSync(path.join(repo,"assets","zero.bin"),Buffer.from([0,1,255]));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));return{root,repo,dst};}
test("LOCAL_FIXTURE_ONLY baseline manifest preserves bytes, modes, empty dirs and remains immutable",t=>{const f=fixture(t);fs.mkdirSync(path.join(f.repo,"empty"));const copy=runtime.copySnapshot(f.repo,f.dst,{requiredPaths:["a.js","assets/zero.bin"]});assert.equal(copy.manifest.schema,"debugai.sandbox-snapshot/v1");assert.equal(copy.manifest.files,2);assert.equal(copy.manifest.entries.find(e=>e.path==="a.js").executable_mode,0o111);assert.ok(copy.manifest.entries.some(e=>e.path==="empty"&&e.type==="directory"));assert.ok(Object.isFrozen(copy.manifest.entries[0]));const digest=copy.manifest.digest;fs.writeFileSync(path.join(f.dst,"a.js"),"candidate only\n");assert.equal(fs.readFileSync(path.join(f.repo,"a.js"),"utf8"),"module.exports=1;\n");assert.equal(copy.manifest.digest,digest);assert.throws(()=>runtime.verifySnapshotCopy(f.dst,copy.manifest),/SNAPSHOT_COPY_MISMATCH/);});
test("LOCAL_FIXTURE_ONLY same revision cannot hide changed bytes or executable mode",t=>{const f=fixture(t),first=runtime.copySnapshot(f.repo,f.dst).manifest;fs.writeFileSync(path.join(f.repo,"a.js"),"module.exports=2;\n");const second=runtime.copySnapshot(f.repo,path.join(f.root,"copy2")).manifest;assert.notEqual(first.digest,second.digest);fs.unlinkSync(path.join(f.repo,"a.js"));fs.writeFileSync(path.join(f.repo,"a.js"),"module.exports=2;\n",{mode:0o644});const third=runtime.copySnapshot(f.repo,path.join(f.root,"copy3")).manifest;assert.notEqual(second.digest,third.digest);});
test("LOCAL_FIXTURE_ONLY missing and excluded required assets never qualify",t=>{for(const rel of ["missing.json","build/native.node","node_modules/pkg/index.js","link.js"]){const f=fixture(t);fs.mkdirSync(path.join(f.repo,"build"));fs.writeFileSync(path.join(f.repo,"build","native.node"),"fixture");fs.symlinkSync(path.join(f.repo,"a.js"),path.join(f.repo,"link.js"));assert.throws(()=>runtime.copySnapshot(f.repo,f.dst,{requiredPaths:[rel]}),/SNAPSHOT_INCOMPLETE/);}});
test("LOCAL_FIXTURE_ONLY traversal, destination overlap and symlink escape fail closed",t=>{const f=fixture(t);assert.throws(()=>runtime.copySnapshot(f.repo,f.dst,{requiredPaths:["../outside.js"]}),/PATH_INVALID/);assert.throws(()=>runtime.copySnapshot(f.repo,path.join(f.repo,"nested")),/SNAPSHOT_DESTINATION/);fs.symlinkSync(f.root,path.join(f.repo,"escape"));const copy=runtime.copySnapshot(f.repo,f.dst);assert.ok(copy.manifest.exclusions.some(e=>e.path==="escape"&&e.reason==="SYMLINK_UNSUPPORTED"));assert.equal(copy.manifest.completeness,"NOT_VERIFIED");assert.throws(()=>runtime.copySnapshot(f.repo,path.join(f.root,"copy2"),{requiredPaths:["escape/outside.js"]}),/SNAPSHOT_INCOMPLETE/);});
test("LOCAL_FIXTURE_ONLY staged omission, extra path, mode and forged manifest PASS are rejected",t=>{for(const mutation of ["omit","extra","mode","forge"]){const f=fixture(t),copy=runtime.copySnapshot(f.repo,f.dst,{requiredPaths:["a.js"]});if(mutation==="omit")fs.unlinkSync(path.join(f.dst,"assets","zero.bin"));if(mutation==="extra")fs.writeFileSync(path.join(f.dst,"extra.js"),"x");if(mutation==="mode"){const file=path.join(f.dst,"a.js"),bytes=fs.readFileSync(file);fs.unlinkSync(file);fs.writeFileSync(file,bytes,{mode:0o644});}let manifest=copy.manifest;if(mutation==="forge"){manifest=structuredClone(manifest);manifest.completeness="PASS";}assert.throws(()=>runtime.verifySnapshotCopy(f.dst,manifest),/SNAPSHOT_(COPY_MISMATCH|MANIFEST_INVALID)/);}});
test("LOCAL_FIXTURE_ONLY job rejects malformed candidate operations and required omission before execution",t=>{const f=fixture(t),input={sourceRepo:f.repo,jobRoot:path.join(f.root,"jobs"),action:"node.check",args:{path:"a.js"}};assert.throws(()=>runtime.prepareSandboxJob({...input,candidate:{id:"fake",pass:true,operations:[{path:"../outside",type:"write"}]}}),/SANDBOX_CANDIDATE_OPERATION_INVALID/);assert.throws(()=>runtime.prepareSandboxJob({...input,requiredPaths:["assets/missing.json"]}),/SNAPSHOT_INCOMPLETE/);const job=runtime.prepareSandboxJob(input);assert.equal(job.request.source_snapshot.manifest.construction,"NOT_CONFIGURED");fs.writeFileSync(path.join(job.job_dir,"repo","a.js"),"changed");let called=false;assert.throws(()=>runtime.runPreparedSandboxJob({jobDir:job.job_dir,spawnSyncImpl(){called=true;return{status:0,stdout:"LANDLOCK_ABI=4"};}}),/SNAPSHOT_COPY_MISMATCH/);assert.equal(called,false);});
test("LOCAL_FIXTURE_ONLY unbound legacy request remains compatible without snapshot qualification",t=>{const f=fixture(t),job=runtime.prepareSandboxJob({sourceRepo:f.repo,jobRoot:path.join(f.root,"jobs"),action:"node.check",args:{path:"a.js"}});const req=job.request;delete req.source_snapshot.manifest;fs.writeFileSync(path.join(job.job_dir,"request.json"),JSON.stringify(req));const result=runtime.runPreparedSandboxJob({jobDir:job.job_dir,spawnSyncImpl:(_cmd,args)=>({status:0,stdout:args[0]==="--probe"?"LANDLOCK_ABI=4":"ok"})});assert.equal(result.pass,true);assert.equal(result.snapshot_qualification,"NOT_VERIFIED");});
test("LOCAL_FIXTURE_ONLY command PASS cannot forge candidate construction or hide a failed exit",()=>{const {toEvidence}=require("../control/sandbox-verification.js"),check={script:"test",check_type:"UNIT"};const result={job_id:"JOB_fixture",pass:true,code:1,timed_out:false};assert.equal(toEvidence(result,check).status,"FAIL");result.code=0;const scoped=toEvidence(result,check);assert.equal(scoped.status,"PASS");assert.equal(scoped.snapshot_completeness,"NOT_VERIFIED");assert.equal(scoped.candidate_construction,"NOT_CONFIGURED");});
test("LOCAL_FIXTURE_ONLY copy protects existing destination and accepts legacy node path spelling",t=>{const f=fixture(t);fs.mkdirSync(f.dst);fs.writeFileSync(path.join(f.dst,"keep"),"untouched");assert.throws(()=>runtime.copySnapshot(f.repo,f.dst),/SNAPSHOT_DESTINATION/);assert.equal(fs.readFileSync(path.join(f.dst,"keep"),"utf8"),"untouched");const job=runtime.prepareSandboxJob({sourceRepo:f.repo,jobRoot:path.join(f.root,"jobs"),action:"node.check",args:{path:"./a.js"}});assert.deepEqual(job.request.source_snapshot.manifest.required_paths,["a.js"]);});
test("LOCAL_FIXTURE_ONLY changed source during staging fails and removes only its own copy",t=>{const f=fixture(t),write=fs.writeFileSync;fs.writeFileSync=function(file,...args){const out=write.call(fs,file,...args);if(file===path.join(f.dst,"a.js"))write.call(fs,path.join(f.repo,"a.js"),"changed during copy\n");return out;};try{assert.throws(()=>runtime.copySnapshot(f.repo,f.dst),/SNAPSHOT_SOURCE_CHANGED/);assert.equal(fs.existsSync(f.dst),false);}finally{fs.writeFileSync=write;}});
test("LOCAL_FIXTURE_ONLY symlinked destination ancestor cannot create directories in source",t=>{const f=fixture(t),alias=path.join(f.root,"alias");fs.symlinkSync(f.repo,alias,"dir");assert.throws(()=>runtime.copySnapshot(f.repo,path.join(alias,"must-not-create","copy")),/SNAPSHOT_DESTINATION/);assert.equal(fs.existsSync(path.join(f.repo,"must-not-create")),false);});
test("LOCAL_FIXTURE_ONLY worktree Git pointer is excluded without reading its contents",t=>{const f=fixture(t);fs.writeFileSync(path.join(f.repo,".git"),"gitdir: /fixture/host-only\n");const copy=runtime.copySnapshot(f.repo,f.dst);assert.equal(fs.existsSync(path.join(f.dst,".git")),false);assert.ok(copy.manifest.exclusions.some(e=>e.path===".git"&&e.reason==="POLICY_EXCLUDED"));assert.equal(JSON.stringify(copy.manifest).includes("host-only"),false);assert.throws(()=>runtime.copySnapshot(f.repo,path.join(f.root,"copy2"),{requiredPaths:[".git"]}),/SNAPSHOT_INCOMPLETE/);});
